import { access, readdir, readFile } from 'node:fs/promises'
import { dirname, relative, resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

function sourcePath(...segments: string[]) {
  return resolve(process.cwd(), ...segments)
}

async function expectFile(path: string) {
  await expect(access(path)).resolves.toBeUndefined()
}

async function collectSourceFiles(rootPath: string): Promise<string[]> {
  try {
    const entries = await readdir(rootPath, { withFileTypes: true })
    const nestedFiles = await Promise.all(
      entries.map((entry) => {
        const entryPath = resolve(rootPath, entry.name)

        if (entry.isDirectory()) {
          return collectSourceFiles(entryPath)
        }

        if (entry.isFile() && /\.(ts|tsx)$/.test(entry.name)) {
          return [entryPath]
        }

        return []
      }),
    )

    return nestedFiles.flat()
  } catch {
    return []
  }
}

async function collectFiles(rootPath: string, pattern: RegExp): Promise<string[]> {
  try {
    const entries = await readdir(rootPath, { withFileTypes: true })
    const nestedFiles = await Promise.all(
      entries.map((entry) => {
        const entryPath = resolve(rootPath, entry.name)

        if (entry.isDirectory()) {
          return collectFiles(entryPath, pattern)
        }

        if (entry.isFile() && pattern.test(entry.name)) {
          return [entryPath]
        }

        return []
      }),
    )

    return nestedFiles.flat()
  } catch {
    return []
  }
}

function extractImportSpecifiers(source: string): string[] {
  const specifiers: string[] = []
  const patterns = [
    /import\s+(?:type\s+)?(?:[^'"]+?\s+from\s+)?['"]([^'"]+)['"]/g,
    /export\s+(?:type\s+)?(?:[^'"]+?\s+from\s+)?['"]([^'"]+)['"]/g,
    /import\s*\(\s*['"]([^'"]+)['"]\s*\)/g,
  ]

  for (const pattern of patterns) {
    for (const match of source.matchAll(pattern)) {
      const specifier = match[1]

      if (specifier) {
        specifiers.push(specifier)
      }
    }
  }

  return specifiers
}

function toCamelCase(value: string) {
  return value.replace(/_([a-z0-9])/g, (_, char: string) => char.toUpperCase())
}

function renderGeneratedHostCommands(commandNames: string[]) {
  const entries = commandNames
    .toSorted((left, right) => left.localeCompare(right))
    .map((commandName) => `  ${toCamelCase(commandName)}: '${commandName}',`)
    .join('\n')

  return `// Generated by apps/desktop/scripts/generate-host-commands.mjs. Do not edit by hand.\n\n/** Host command protocol names generated from Tauri command function names. */\nexport const HOST_COMMANDS = {\n${entries}\n} as const\n\nexport type HostCommandName = (typeof HOST_COMMANDS)[keyof typeof HOST_COMMANDS]\n`
}

function topLevelFeatureFromPath(filePath: string): string | null {
  const relativePath = relative(sourcePath('src/features'), filePath)
  const [featureName] = relativePath.split(/[\\/]/)

  if (!featureName || featureName === '..' || featureName.startsWith('..')) {
    return null
  }

  return featureName
}

function topLevelFeatureFromSpecifier(filePath: string, specifier: string): string | null {
  if (specifier.startsWith('@features/')) {
    return specifier.slice('@features/'.length).split('/')[0] ?? null
  }

  if (!specifier.startsWith('.')) {
    return null
  }

  const resolvedImportPath = resolve(dirname(filePath), specifier)
  const relativeToFeatures = relative(sourcePath('src/features'), resolvedImportPath)

  if (relativeToFeatures.startsWith('..') || relativeToFeatures === '') {
    return null
  }

  return topLevelFeatureFromPath(resolvedImportPath)
}

function specifierTargetsSourceRoot(filePath: string, specifier: string, root: string): boolean {
  const rootAlias = `@${root.replace(/^src\//, '')}`
  if (specifier === rootAlias || specifier.startsWith(`${rootAlias}/`)) {
    return true
  }

  if (specifier === root || specifier.startsWith(`${root}/`)) {
    return true
  }

  if (!specifier.startsWith('.')) {
    return false
  }

  const resolvedImportPath = resolve(dirname(filePath), specifier)
  const relativeToRoot = relative(sourcePath(root), resolvedImportPath)

  return relativeToRoot === '' || (!relativeToRoot.startsWith('..') && !relativeToRoot.startsWith('/'))
}

const TEST_FILE_PATTERN = /\.(test|spec)\.(ts|tsx)$/
const REMOVED_DESKTOP_FACADE_SPECIFIER = '@platform/' + 'desktop'

describe('frontend module architecture', () => {
  it('exposes the FSD foundation roots and mounts app/App directly', async () => {
    await expectFile(sourcePath('src/app/App.tsx'))
    await expectFile(sourcePath('src/app/App.test.tsx'))
    await expectFile(sourcePath('src/app/app-shell/index.ts'))
    await expectFile(sourcePath('src/app/providers/PlatformProvider.tsx'))
    await expectFile(sourcePath('src/app/providers/platformContext.ts'))
    await expectFile(sourcePath('src/app/providers/usePlatformPorts.ts'))
    await expectFile(sourcePath('src/app/registry-setup.ts'))
    await expect(access(sourcePath('src/pages/index.ts'))).rejects.toThrow()
    await expect(access(sourcePath('src/widgets/index.ts'))).rejects.toThrow()
    await expect(access(sourcePath('src/entities/index.ts'))).rejects.toThrow()
    await expectFile(sourcePath('src/shared/contracts/registry.ts'))
    await expectFile(sourcePath('src/shared/contracts/events.ts'))
    await expectFile(sourcePath('src/shared/contracts/commands.ts'))
    await expectFile(sourcePath('src/shared/contracts/platform.ts'))
    await expectFile(sourcePath('src/shared/contracts/types/index.ts'))
    await expectFile(sourcePath('src/shared/contracts/types/workspaceLayout.ts'))
    await expectFile(sourcePath('src/shared/contracts/types/workspaceRuntime.ts'))
    await expectFile(sourcePath('src/shared/contracts/types/cpMaker.ts'))
    await expectFile(sourcePath('src/shared/contracts/types/desktop.ts'))
    await expectFile(sourcePath('src/shared/contracts/types/appUiState.ts'))
    await expectFile(sourcePath('src/shared/contracts/types/modBrowser.ts'))
    await expect(access(sourcePath('src/shared/contracts/types/panelTypes.ts'))).rejects.toThrow()
    await expectFile(sourcePath('src/shared/contracts/types/viewport.ts'))
    await expectFile(sourcePath('src/shared/contracts/types/maps.ts'))
    await expectFile(sourcePath('src/platform/tauri/index.ts'))
    await expectFile(sourcePath('src/platform/electron/index.ts'))

    const mainEntry = await readFile(sourcePath('src/main.tsx'), 'utf8')
    const appEntry = await readFile(sourcePath('src/app/App.tsx'), 'utf8')
    const appShellSource = await readFile(sourcePath('src/app/app-shell/AppShell.tsx'), 'utf8')
    const appShellBridge = await readFile(sourcePath('src/app/app-shell/index.ts'), 'utf8')

    expect(mainEntry).toContain("import('@platform/tauri/devLauncherMock')")
    expect(mainEntry).toContain("import('@app/App')")
    expect(mainEntry).not.toContain("from './App'")
    expect(mainEntry.indexOf("import('@platform/tauri/devLauncherMock')")).toBeLessThan(mainEntry.indexOf("import('@app/App')"))
    expect(mainEntry).toContain('import.meta.env.DEV')
    expect(appEntry).toContain("from '@app/app-shell/AppShell'")
    expect(appEntry).toContain("from '@app/providers/PlatformProvider'")
    expect(appEntry).toContain("from '@app/providers/LauncherPlatformProvider'")
    expect(appEntry).not.toContain('CpMakerPlatformProvider')
    expect(appShellSource).not.toContain("from '@app/registry-setup'")
    expect(appShellSource).toContain("import('@app/registry-setup')")
    expect(appShellSource).not.toContain("from '../providers/CpMakerPlatformProvider'")
    expect(appShellSource).toContain("import('../providers/CpMakerPlatformProvider')")
    expect(appShellBridge).toContain("from './AppShell'")
  })

  it('defines shared contracts without creating runtime instances in shared', async () => {
    const registry = await readFile(sourcePath('src/shared/contracts/registry.ts'), 'utf8')
    const events = await readFile(sourcePath('src/shared/contracts/events.ts'), 'utf8')
    const commands = await readFile(sourcePath('src/shared/contracts/commands.ts'), 'utf8')
    const platform = await readFile(sourcePath('src/shared/contracts/platform.ts'), 'utf8')
    const registrySetup = await readFile(sourcePath('src/app/registry-setup.ts'), 'utf8')

    expect(registry).toContain('export type RegistryItemKind')
    expect(registry).toContain('export type WorkbenchViewRegistration')
    expect(registry).toContain('export interface AppRegistry')
    expect(registry).not.toContain('createAppRegistry(')
    expect(registry).not.toContain('new Map')
    expect(events).toContain('export type AppEvent')
    expect(events).toContain('export type WorkbenchEvent')
    expect(events).toContain('export type CpMakerEvent')
    expect(commands).toContain('export type AppCommand')
    expect(commands).toContain('export interface CommandDispatcher')
    expect(commands).toContain('export type NavigationCommand')
    expect(platform).toContain('export interface FileSystemPort')
    expect(platform).toContain('export interface DesktopWindowPort')
    expect(platform).toContain('export interface StoragePort')
    expect(platform).toContain('export interface DialogPort')
    expect(platform).toContain('export interface PlatformPorts')
    expect(registrySetup).toContain('createAppRegistry(')
    expect(registrySetup).toContain("viewId: 'studio-desk'")
    expect(registrySetup).toContain("viewId: 'workspace-editor'")
    expect(registrySetup).toContain("panelId: 'assets'")
    expect(registrySetup).toContain("panelId: 'viewport'")
    expect(registrySetup).toContain('getWorkbenchViewRegistration')
    expect(registrySetup).toContain('getWorkspacePanelRegistration')
  })

  it('provides platform ports from the app layer through desktop host adapters', async () => {
    const provider = await readFile(sourcePath('src/app/providers/PlatformProvider.tsx'), 'utf8')
    const cpMakerProvider = await readFile(sourcePath('src/app/providers/CpMakerPlatformProvider.tsx'), 'utf8')
    const cpMakerPortAdapter = await readFile(sourcePath('src/app/providers/cpMakerPortAdapter.ts'), 'utf8')
    const cpMakerProviderEntry = await readFile(sourcePath('src/features/cp-maker/provider.ts'), 'utf8')
    const tauriAdapter = await readFile(sourcePath('src/platform/tauri/index.ts'), 'utf8')
    const electronAdapter = await readFile(sourcePath('src/platform/electron/index.ts'), 'utf8')

    expect(provider).toContain('PlatformProvider')
    expect(cpMakerProvider).toContain("from '@features/cp-maker/provider'")
    expect(cpMakerProvider).not.toContain("from '@features/cp-maker'")
    expect(cpMakerPortAdapter).toContain("from '@features/cp-maker/provider'")
    expect(cpMakerPortAdapter).not.toContain("from '@features/cp-maker'")
    expect(cpMakerProviderEntry).toContain('Lightweight cp-maker provider entry')
    expect(cpMakerProviderEntry).toContain("from './model/cpMakerProvider'")
    expect(cpMakerProviderEntry).toContain("from './model/useCpMakerPort'")
    expect(cpMakerProviderEntry).toContain("from './model/cpMakerPort'")
    expect(cpMakerProviderEntry).not.toContain("from './ui/")
    expect(cpMakerProviderEntry).not.toContain("from './state/")
    expect(cpMakerProviderEntry).not.toContain("from './routing/")
    const platformContext = await readFile(sourcePath('src/app/providers/platformContext.ts'), 'utf8')
    const usePlatformPorts = await readFile(sourcePath('src/app/providers/usePlatformPorts.ts'), 'utf8')

    expect(platformContext).toContain('createContext<PlatformPorts')
    expect(usePlatformPorts).toContain('usePlatformPorts')
    expect(tauriAdapter).toContain("from '@shared/contracts'")
    expect(tauriAdapter).toContain("from '@tauri-apps/api/core'")
    expect(tauriAdapter).toContain("from '@tauri-apps/api/window'")
    expect(tauriAdapter).toContain("from '@tauri-apps/plugin-dialog'")
    expect(tauriAdapter).toContain('createTauriPlatformPorts')
    expect(electronAdapter).toContain("from '@shared/contracts'")
    expect(electronAdapter).toContain('createElectronPlatformPorts')
    expect(electronAdapter).toContain('window.modforgeElectron')
    expect(provider).toContain('isElectronHost()')
  })

  it('keeps Electron force close bypassing renderer beforeunload guards', async () => {
    const electronMain = await readFile(sourcePath('electron/main.ts'), 'utf8')
    const forceCloseHandler = electronMain.match(/ipcMain\.handle\('modforge:window-force-close'[\s\S]*?\n\}\)/)?.[0] ?? ''

    expect(forceCloseHandler).toContain('window.destroy()')
    expect(forceCloseHandler).not.toContain('window.close()')
    expect(electronMain).toContain('class SidecarTransport')
    expect(electronMain).toContain('stop()')
    expect(electronMain).toContain('sidecarStdout?.close()')
  })

  it('keeps host command policy declared by call sites instead of a default command table', async () => {
    const runtime = await readFile(sourcePath('src/shared/lib/desktop/runtime.ts'), 'utf8')
    const hostCommandClient = await readFile(sourcePath('src/shared/lib/host-command-client/index.ts'), 'utf8')

    expect(runtime).not.toContain('defaultHostCommandPolicy')
    expect(hostCommandClient).not.toContain('defaultHostCommandPolicy')
    expect(runtime).toContain('policy: HostCommandPolicy')
    expect(runtime).not.toContain('policy?: HostCommandPolicy')
  })

  it('keeps launcher library drag measuring out of the always-on layout path', async () => {
    const launcherLibraryPage = await readFile(sourcePath('src/pages/launcher/ui/LauncherLibraryPage.tsx'), 'utf8')

    expect(launcherLibraryPage).not.toContain('MeasuringStrategy.Always')
  })

  it('keeps new layer path aliases synchronized across TypeScript, Vite, and Vitest', async () => {
    const tsconfig = await readFile(sourcePath('tsconfig.app.json'), 'utf8')
    const viteConfig = await readFile(sourcePath('vite.config.ts'), 'utf8')
    const vitestConfig = await readFile(sourcePath('vitest.config.ts'), 'utf8')

    for (const alias of ['@app', '@pages', '@widgets', '@entities', '@shared']) {
      expect(tsconfig).toContain(`"${alias}/*"`)
      expect(viteConfig).toContain(`'${alias}'`)
      expect(vitestConfig).toContain(`'${alias}'`)
    }
  })

  it('blocks raw invoke calls from business layers', async () => {
    const scannedRoots = ['src/pages', 'src/widgets', 'src/features', 'src/entities', 'src/shared']
    const sourceFiles = await Promise.all(scannedRoots.map((root) => collectSourceFiles(sourcePath(root))))
    const allowedInvokeFiles = new Set(['src/shared/lib/host-command-client/index.ts', 'src/shared/lib/host-command-client/index.test.ts'])
    const violations: string[] = []

    for (const filePath of sourceFiles.flat()) {
      const source = await readFile(filePath, 'utf8')
      const relativePath = filePath.replace(`${process.cwd()}/`, '')

      if (!allowedInvokeFiles.has(relativePath) && /\binvoke\s*\(/.test(source)) {
        violations.push(`${relativePath} calls invoke(`)
      }
    }

    expect(violations).toEqual([])
  }, 10000)

  it('blocks business and provider code from bypassing HostCommandClient with raw file system commands', async () => {
    const scannedRoots = ['src/app', 'src/pages', 'src/widgets', 'src/features', 'src/entities']
    const sourceFiles = await Promise.all(scannedRoots.map((root) => collectSourceFiles(sourcePath(root))))
    const violations: string[] = []

    for (const filePath of sourceFiles.flat()) {
      const source = await readFile(filePath, 'utf8')
      if (!source.includes('fileSystem.invokeCommand')) {
        continue
      }
      const relativePath = relative(sourcePath(), filePath).replaceAll('\\', '/')
      violations.push(`${relativePath} calls fileSystem.invokeCommand`)
    }

    expect(violations).toEqual([])
  }, 10000)

  it('keeps generated host command constants in sync with Tauri command function names', async () => {
    const commandFiles = await collectFiles(sourcePath('src-tauri/src/commands'), /\.rs$/)
    const commandNames: string[] = []

    for (const filePath of commandFiles) {
      if (filePath.endsWith('/runtime.rs')) {
        continue
      }
      const source = await readFile(filePath, 'utf8')
      for (const match of source.matchAll(/#\[tauri::command\]\s*pub fn ([a-z][a-z0-9_]*)/g)) {
        commandNames.push(match[1] ?? '')
      }
    }

    const generated = await readFile(sourcePath('src/shared/contracts/generated/hostCommands.ts'), 'utf8')
    expect(generated).toBe(renderGeneratedHostCommands(commandNames.filter(Boolean)))
  })

  it('requires typed host command constants for desktop business invocations', async () => {
    const scannedRoots = ['src/pages', 'src/widgets', 'src/features', 'src/entities', 'src/shared/lib/desktop']
    const sourceFiles = await Promise.all(scannedRoots.map((root) => collectSourceFiles(sourcePath(root))))
    const allowedFiles = new Set(['src/shared/lib/desktop/runtime.ts'])
    const violations: string[] = []

    for (const filePath of sourceFiles.flat()) {
      const relativePath = relative(sourcePath(), filePath).replaceAll('\\', '/')
      if (allowedFiles.has(relativePath) || TEST_FILE_PATTERN.test(filePath)) {
        continue
      }

      const source = await readFile(filePath, 'utf8')
      if (/invokeDesktop(?:<[^>]+>)?\(\s*['"][a-z][a-z0-9_]+['"]/.test(source)) {
        violations.push(`${relativePath} passes a raw host command string to invokeDesktop`)
      }
    }

    expect(violations).toEqual([])
  }, 10000)

  it('keeps Tauri API imports inside approved adapter and test boundaries', async () => {
    const sourceFiles = await collectSourceFiles(sourcePath('src'))
    const allowedImportFiles = new Set(['src/platform/tauri/index.ts', 'src/platform/tauri/devLauncherMock.ts'])
    const violations: string[] = []

    for (const filePath of sourceFiles) {
      if (TEST_FILE_PATTERN.test(filePath)) {
        continue
      }

      const source = await readFile(filePath, 'utf8')
      if (!source.includes('@tauri-apps/api')) {
        continue
      }

      const relativePath = relative(sourcePath(), filePath).replaceAll('\\', '/')
      if (!allowedImportFiles.has(relativePath)) {
        violations.push(`${relativePath} imports @tauri-apps/api outside approved adapter boundary`)
      }
    }

    expect(violations).toEqual([])
  }, 10000)

  it('blocks null Suspense fallbacks in covered page-level loading entry points', async () => {
    const coveredEntryFiles = [
      'src/app/app-shell/AppShell.tsx',
      'src/pages/workbench/ui/WorkbenchPage.tsx',
      'src/pages/workbench/ui/WorkbenchExperience.tsx',
    ]
    const violations: string[] = []

    for (const file of coveredEntryFiles) {
      const source = await readFile(sourcePath(file), 'utf8')

      if (/fallback\s*=\s*\{\s*null\s*\}/.test(source)) {
        violations.push(`${file} uses fallback={null}`)
      }

      if (!source.includes('@shared/ui/loading-motion')) {
        const usesApprovedWorkbenchSkeleton = source.includes('@shared/ui/WorkbenchShellSkeleton')

        if (!usesApprovedWorkbenchSkeleton) {
          violations.push(`${file} does not consume shared loading-motion UI or the approved workbench shell skeleton`)
        }
      }
    }

    expect(violations).toEqual([])
  })

  it('blocks feature-to-feature imports', async () => {
    const featureFiles = await collectSourceFiles(sourcePath('src/features'))
    const featureViolations: string[] = []

    for (const filePath of featureFiles) {
      const source = await readFile(filePath, 'utf8')
      const ownerFeature = topLevelFeatureFromPath(filePath)

      if (!ownerFeature) {
        continue
      }

      for (const specifier of extractImportSpecifiers(source)) {
        const importedFeature = topLevelFeatureFromSpecifier(filePath, specifier)

        if (importedFeature && importedFeature !== ownerFeature) {
          const relativePath = filePath.replace(`${process.cwd()}/`, '')
          featureViolations.push(`${relativePath} imports ${specifier}`)
        }
      }
    }

    expect(featureViolations).toEqual([])
  }, 10000)

  it('enforces long-term frontend import graph boundaries', async () => {
    const rules = [
      {
        root: 'src/features',
        blockedTargets: ['src/app', 'src/pages', 'src/widgets', 'src/platform'],
        message: 'features must not depend on upper layers or platform adapters',
      },
      {
        root: 'src/widgets',
        blockedTargets: ['src/app', 'src/pages', 'src/platform'],
        message: 'widgets must not depend on app/page assembly or platform adapters',
      },
      {
        root: 'src/pages',
        blockedTargets: ['src/app'],
        message: 'pages must not depend upward on app assembly',
      },
      {
        root: 'src/entities',
        blockedTargets: ['src/pages', 'src/widgets', 'src/features'],
        message: 'entities must stay headless and below pages/widgets/features',
      },
    ]
    const violations: string[] = []

    for (const rule of rules) {
      const sourceFiles = await collectSourceFiles(sourcePath(rule.root))

      for (const filePath of sourceFiles) {
        const source = await readFile(filePath, 'utf8')
        const relativePath = relative(sourcePath(), filePath).replace(/\\/g, '/')

        for (const specifier of extractImportSpecifiers(source)) {
          for (const blockedTarget of rule.blockedTargets) {
            if (specifierTargetsSourceRoot(filePath, specifier, blockedTarget)) {
              violations.push(`${relativePath} imports ${specifier}: ${rule.message}`)
            }
          }
        }
      }
    }

    expect(violations).toEqual([])
  }, 30000)

  it('keeps entities independent of workbench panel and layout contracts', async () => {
    const entityFiles = await collectSourceFiles(sourcePath('src/entities'))
    const blockedContractSpecifiers = new Set([
      '@shared/contracts/types/workspaceLayout',
      '@shared/contracts/types/workspaceRuntime',
      '@shared/contracts/types/panelTypes',
    ])
    const blockedTerms = [
      'WorkspaceLayout',
      'WorkspacePanel',
      'WorkspacePanelMeta',
      'WorkspacePanelDefinition',
      'DockArea',
      'workspace-panels',
      'panelTypes',
      'workspaceLayout',
      'workspaceRuntime',
    ]
    const violations: string[] = []

    for (const filePath of entityFiles) {
      const source = await readFile(filePath, 'utf8')
      const relativePath = relative(sourcePath(), filePath).replace(/\\/g, '/')

      for (const specifier of extractImportSpecifiers(source)) {
        if (blockedContractSpecifiers.has(specifier) || specifier.includes('workspace-panels')) {
          violations.push(`${relativePath} imports ${specifier}`)
        }
      }

      for (const blockedTerm of blockedTerms) {
        if (source.includes(blockedTerm)) {
          violations.push(`${relativePath} references ${blockedTerm}`)
        }
      }
    }

    expect(violations).toEqual([])
  }, 30000)

  it('blocks cp-maker segment public APIs outside the slice root', async () => {
    const scannedRoots = ['src/app', 'src/pages', 'src/widgets', 'src/features', 'src/platform']
    const sourceFiles = await Promise.all(scannedRoots.map((root) => collectSourceFiles(sourcePath(root))))
    const violations: string[] = []
    const blockedSpecifiers = [
      '@features/cp-maker/model',
      '@features/cp-maker/routing',
      '@features/cp-maker/state',
      '@features/cp-maker/ui',
    ]

    for (const filePath of sourceFiles.flat()) {
      if (filePath.includes(`${sourcePath('src/features/cp-maker')}\\`) || filePath.includes(`${sourcePath('src/features/cp-maker')}/`)) {
        continue
      }

      const source = await readFile(filePath, 'utf8')
      const relativePath = filePath.replace(`${process.cwd()}/`, '')

      for (const specifier of extractImportSpecifiers(source)) {
        if (blockedSpecifiers.some((blockedSpecifier) => specifier === blockedSpecifier || specifier.startsWith(`${blockedSpecifier}/`))) {
          violations.push(`${relativePath} imports ${specifier}`)
        }
      }
    }

    expect(violations).toEqual([])
  }, 30000)

  it('keeps launcher initial entries off heavy feature and entity barrels', async () => {
    const initialEntryFiles = [
      'src/app/app-shell/AppShell.tsx',
      'src/pages/launcher/LauncherPage.tsx',
      'src/pages/launcher/ui/LauncherShell.tsx',
      'src/pages/launcher/ui/LauncherLibraryPage.tsx',
      'src/pages/launcher/ui/LauncherDownloadsPopover.tsx',
    ]
    const blockedSpecifiers = ['@features/launcher', '@features/cp-maker', '@entities/event', '@entities/map']
    const violations: string[] = []

    for (const file of initialEntryFiles) {
      const source = await readFile(sourcePath(file), 'utf8')
      for (const specifier of extractImportSpecifiers(source)) {
        if (blockedSpecifiers.includes(specifier)) {
          violations.push(`${file} imports ${specifier}`)
        }
      }
    }

    expect(violations).toEqual([])
  })

  it('blocks removed component and lib path references', async () => {
    const scannedRoots = ['src/app', 'src/pages', 'src/widgets', 'src/features', 'src/entities', 'src/shared', 'src/platform']
    const sourceFiles = await Promise.all(scannedRoots.map((root) => collectSourceFiles(sourcePath(root))))
    const removedPathPatterns = [
      'src/components',
      'src/lib',
      'components/',
      'components/event-workflow',
      'components/cp-maker',
      'components/map-workflow',
      'components/image-workflow',
      'map-workflow',
      'image-workflow',
    ]
    const removedPathViolations: string[] = []

    for (const filePath of sourceFiles.flat()) {
      const source = await readFile(filePath, 'utf8')
      const relativePath = filePath.replace(`${process.cwd()}/`, '')

      for (const pattern of removedPathPatterns) {
        if (source.includes(pattern)) {
          removedPathViolations.push(`${relativePath} contains ${pattern}`)
        }
      }

      for (const specifier of extractImportSpecifiers(source)) {
        if (!specifier.startsWith('.')) {
          continue
        }

        const resolvedImportPath = resolve(dirname(filePath), specifier)
        const relativeToLegacyComponents = relative(sourcePath('src/components'), resolvedImportPath)
        const relativeToLegacyLib = relative(sourcePath('src/lib'), resolvedImportPath)
        const importsLegacyComponents =
          relativeToLegacyComponents === '' || (!relativeToLegacyComponents.startsWith('..') && !relativeToLegacyComponents.startsWith('/'))
        const importsLegacyLib =
          relativeToLegacyLib === '' || (!relativeToLegacyLib.startsWith('..') && !relativeToLegacyLib.startsWith('/'))

        if (importsLegacyComponents || importsLegacyLib) {
          removedPathViolations.push(`${relativePath} imports ${specifier}`)
        }
      }
    }

    expect(removedPathViolations).toEqual([])
  }, 30000)

  it('blocks removed feature-owned workspace paths', async () => {
    const scannedRoots = ['src/app', 'src/pages', 'src/widgets', 'src/features', 'src/entities', 'src/shared', 'src/platform']
    const sourceFiles = await Promise.all(scannedRoots.map((root) => collectSourceFiles(sourcePath(root))))
    const workspaceViolations: string[] = []

    for (const filePath of sourceFiles.flat()) {
      const source = await readFile(filePath, 'utf8')
      const relativePath = filePath.replace(`${process.cwd()}/`, '')

      if (source.includes('@features/workspaces') || source.includes('features/workspaces')) {
        workspaceViolations.push(`${relativePath} contains removed workspace path reference`)
      }
    }

    expect(workspaceViolations).toEqual([])
    await expect(access(sourcePath('src/features/workspaces'))).rejects.toThrow()
  })

  it('keeps shared modules free of upper-layer imports and desktop bridge calls', async () => {
    const sharedSourceFiles = await collectSourceFiles(sourcePath('src/shared'))
    const sharedViolations: string[] = []
    const blockedSharedSpecifiers = [
      '@app/',
      '@entities/',
      '@features/',
      '@pages/',
      '@platform/',
      '@widgets/',
      '../../app',
      '../../components',
      '../../pages',
      '../../lib/app',
      '../../lib/desktop',
      '../../platform',
      '../app',
      '../components',
      '../pages',
      '../lib/app',
      '../lib/desktop',
      '../platform',
    ]

    for (const filePath of sharedSourceFiles) {
      const source = await readFile(filePath, 'utf8')
      const relativePath = filePath.replace(`${process.cwd()}/`, '')

      for (const specifier of extractImportSpecifiers(source)) {
        if (blockedSharedSpecifiers.some((blockedSpecifier) => specifier === blockedSpecifier || specifier.startsWith(blockedSpecifier))) {
          sharedViolations.push(`${relativePath} imports ${specifier}`)
        }
      }
    }

    expect(sharedViolations).toEqual([])

    const sharedTypesIndex = await readFile(sourcePath('src/shared/contracts/types/index.ts'), 'utf8')

    expect(sharedTypesIndex).toContain("export type * from './workspaceLayout'")
    expect(sharedTypesIndex).toContain("export type * from './cpMaker'")
    expect(sharedTypesIndex).toContain("export type * from './modBrowser'")
    expect(sharedTypesIndex).not.toContain("export type * from './panelTypes'")
    expect(sharedTypesIndex).toContain("export type * from './viewport'")
    expect(sharedTypesIndex).toContain("export type * from './maps'")
    expect(sharedTypesIndex).toContain("export type * from './workspaceRuntime'")
    expect(sharedTypesIndex).toContain("export type * from './desktop'")
    expect(sharedTypesIndex).toContain("export type * from './appUiState'")
    expect(sharedTypesIndex).not.toContain(`export type * from '${REMOVED_DESKTOP_FACADE_SPECIFIER}'`)
  })

  it('keeps shared desktop exports limited to host infrastructure APIs', async () => {
    const sharedDesktopIndex = await readFile(sourcePath('src/shared/lib/desktop/index.ts'), 'utf8')
    const blockedDomainExports = [
      'LauncherGameLaunchResult',
      'launchLauncherGame',
      'loadLauncher',
      'saveLauncher',
      'scanLauncher',
      'ContentPatcher',
      'CpMaker',
      'ModProject',
      'GameDirectoryInfo',
      'MapAsset',
      'loadMapAsset',
      'loadTextAsset',
      'scanMaps',
      'scanEvents',
    ]

    for (const blockedExport of blockedDomainExports) {
      expect(sharedDesktopIndex).not.toContain(blockedExport)
    }
  })

  /**
   * Platform boundary classification: the removed desktop platform facade was a migration facade.
   * It must not return as a production or test import path.
   */
  it('blocks the removed desktop platform facade from returning', async () => {
    await expect(access(sourcePath('src/platform/desktop'))).rejects.toThrow()

    const allFiles = await collectSourceFiles(sourcePath('src'))
    const violations: string[] = []

    for (const filePath of allFiles) {
      const source = await readFile(filePath, 'utf8')
      const relPath = relative(sourcePath('src'), filePath).replace(/\\/g, '/')

      for (const specifier of extractImportSpecifiers(source)) {
        if (specifier === REMOVED_DESKTOP_FACADE_SPECIFIER) {
          violations.push(`${relPath} imports ${REMOVED_DESKTOP_FACADE_SPECIFIER}`)
        }
      }
    }

    expect(violations).toEqual([])
  }, 30000)

  it('blocks active Nexus Public HTML and Cloudflare verification paths', async () => {
    const scannedRoots = ['src/app', 'src/pages', 'src/widgets', 'src/features', 'src/shared', 'src/platform']
    const sourceFiles = await Promise.all(scannedRoots.map((root) => collectSourceFiles(sourcePath(root))))
    const blockedPatterns = [
      /publicHtml/i,
      /Public HTML/,
      /Cloudflare/,
      /cloudflare/,
      /cf_clearance/,
      /launcher\/cloudflare-challenge-required/,
      /public_html_nexus_/,
    ]
    const violations: string[] = []

    for (const filePath of sourceFiles.flat()) {
      const source = await readFile(filePath, 'utf8')
      const relPath = relative(sourcePath('src'), filePath).replace(/\\/g, '/')

      for (const pattern of blockedPatterns) {
        if (pattern.test(source)) {
          violations.push(`${relPath} contains ${pattern}`)
        }
      }
    }

    await expect(access(sourcePath('src/app/webview-surfaces/PublicHtmlVerificationControlsSurface.tsx'))).rejects.toThrow()
    expect(violations).toEqual([])
  }, 30000)

  it('keeps NexusMods provider code outside the launcher Rust domain', async () => {
    const launcherFiles = await collectSourceFiles(sourcePath('src-tauri/src/domain/launcher'))
    const blockedPatterns = [
      /api-router\.nexusmods\.com/,
      /api\.nexusmods\.com/,
      /graphql\.nexusmods\.com/,
      /staticdelivery\.nexusmods\.com/,
      /send_nexus_(json_)?request/,
      /api_headers/,
      /graphql_headers/,
      /public_graphql_headers/,
      /^pub mod (catalog|discovery|downloads_provider|http|mod_detail|remote|rest_api|session|shared|sso);/m,
    ]
    const violations: string[] = []

    for (const filePath of launcherFiles) {
      const source = await readFile(filePath, 'utf8')
      const relPath = relative(sourcePath('src-tauri/src/domain/launcher'), filePath).replace(/\\/g, '/')

      for (const pattern of blockedPatterns) {
        if (pattern.test(source)) {
          violations.push(`${relPath} contains ${pattern}`)
        }
      }
    }

    expect(violations).toEqual([])
  }, 30000)

  it('rejects page-specific workbench panel source files under dock-side folder names', async () => {
    const panelsRoot = sourcePath('src/pages/workbench/ui/workspace-panels')
    const allowedDomainFolders = new Set(['event', 'building', 'character', 'map', 'item', 'mod', 'common'])

    let panelsDir
    try {
      panelsDir = await readdir(panelsRoot, { withFileTypes: true })
    } catch {
      return
    }

    const violations: string[] = []

    for (const entry of panelsDir) {
      if (!entry.isDirectory()) {
        continue
      }

      if (allowedDomainFolders.has(entry.name)) {
        continue
      }

      violations.push(
        'workspace-panels/' + entry.name + ' is not an allowed domain folder. Allowed: ' + Array.from(allowedDomainFolders).join(', '),
      )
    }

    expect(violations).toEqual([])
  }, 10000)
})
