use crate::AppHandle;
use crate::domain;
use crate::host_runtime::{DispatchContext, HostCommand};
use crate::host_runtime::{
    HostCommandResourceLocks, HostCommandResponse, HostCommandResponseWriter, HostCommandScheduler,
    HostCommandSchedulerConfig, ResolvedCommandOrResponse,
};
use crate::support::logging::{self, DebugLoggingState, LogEvent, targets};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::io::{self, BufRead, Write};
use std::sync::{Arc, Mutex};

#[derive(Debug, Deserialize)]
pub(crate) struct RpcRequest {
    pub(crate) id: Value,
    pub(crate) command: String,
    #[serde(default)]
    pub(crate) args: Value,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct HostEventFrame<'a> {
    event: &'a str,
    payload: Value,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct RpcEventFrame<'a> {
    event: HostEventFrame<'a>,
}

/// Resolves a typed command binding from a wire frame: deserializes the
/// args into the command's wire envelope `P` exactly once and delegates to
/// `HostCommand::resolve`, the same builder the Tauri path runs in-process.
pub(crate) fn resolve_typed<P: HostCommand>(
    ctx: &DispatchContext,
    id: Value,
    args: Value,
) -> ResolvedCommandOrResponse {
    let params = match serde_json::from_value::<P>(if args.is_null() { json!({}) } else { args }) {
        Ok(params) => params,
        Err(error) => {
            return ResolvedCommandOrResponse::Response(HostCommandResponse {
                id,
                ok: false,
                result: None,
                error: Some(json!(format!(
                    "Invalid command arguments for {}: {error}",
                    P::NAME
                ))),
            });
        }
    };
    P::resolve(ctx, id, params)
}

pub(crate) fn resolve_command(
    ctx: &DispatchContext,
    request: RpcRequest,
) -> ResolvedCommandOrResponse {
    let RpcRequest { id, command, args } = request;

    match command.as_str() {
        // Generated by apps/desktop/scripts/generate-host-commands.mjs. Do not edit by hand.
        // domain::ai::commands
        crate::host_command_wire!(apply_ai_profiles_import) => resolve_typed::<
            crate::domain::ai::commands::ApplyAiProfilesImportParams,
        >(ctx, id, args),
        crate::host_command_wire!(cancel_ai_job) => resolve_typed::<
            crate::domain::ai::commands::CancelAiJobParams,
        >(ctx, id, args),
        crate::host_command_wire!(clear_ai_translation_cache) => resolve_typed::<
            crate::domain::ai::commands::ClearAiTranslationCacheParams,
        >(ctx, id, args),
        crate::host_command_wire!(export_ai_profiles) => resolve_typed::<
            crate::domain::ai::commands::ExportAiProfilesParams,
        >(ctx, id, args),
        crate::host_command_wire!(fetch_ai_models_dev_catalog) => resolve_typed::<
            crate::domain::ai::commands::FetchAiModelsDevCatalogParams,
        >(ctx, id, args),
        crate::host_command_wire!(get_ai_translation_cache_stats) => resolve_typed::<
            crate::domain::ai::commands::GetAiTranslationCacheStatsParams,
        >(ctx, id, args),
        crate::host_command_wire!(list_ai_models) => resolve_typed::<
            crate::domain::ai::commands::ListAiModelsParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_ai_settings) => resolve_typed::<
            crate::domain::ai::commands::LoadAiSettingsParams,
        >(ctx, id, args),
        crate::host_command_wire!(preview_ai_profiles_import) => resolve_typed::<
            crate::domain::ai::commands::PreviewAiProfilesImportParams,
        >(ctx, id, args),
        crate::host_command_wire!(read_ai_translation_cache) => resolve_typed::<
            crate::domain::ai::commands::ReadAiTranslationCacheParams,
        >(ctx, id, args),
        crate::host_command_wire!(save_ai_settings) => resolve_typed::<
            crate::domain::ai::commands::SaveAiSettingsParams,
        >(ctx, id, args),
        crate::host_command_wire!(test_ai_profile) => resolve_typed::<
            crate::domain::ai::commands::TestAiProfileParams,
        >(ctx, id, args),
        crate::host_command_wire!(translate_ai_batch) => resolve_typed::<
            crate::domain::ai::commands::TranslateAiBatchParams,
        >(ctx, id, args),
        crate::host_command_wire!(write_ai_translation_cache) => resolve_typed::<
            crate::domain::ai::commands::WriteAiTranslationCacheParams,
        >(ctx, id, args),
        // domain::app_ui::commands
        crate::host_command_wire!(load_app_ui_state) => resolve_typed::<
            crate::domain::app_ui::commands::LoadAppUiStateParams,
        >(ctx, id, args),
        crate::host_command_wire!(patch_app_ui_state) => resolve_typed::<
            crate::domain::app_ui::commands::PatchAppUiStateParams,
        >(ctx, id, args),
        // domain::assets::commands
        crate::host_command_wire!(clear_file_cache) => resolve_typed::<
            crate::domain::assets::commands::ClearFileCacheParams,
        >(ctx, id, args),
        crate::host_command_wire!(detect_default_game_directory) => resolve_typed::<
            crate::domain::assets::commands::DetectDefaultGameDirectoryParams,
        >(ctx, id, args),
        crate::host_command_wire!(export_file) => resolve_typed::<
            crate::domain::assets::commands::ExportFileParams,
        >(ctx, id, args),
        crate::host_command_wire!(export_map_png) => resolve_typed::<
            crate::domain::assets::commands::ExportMapPngParams,
        >(ctx, id, args),
        crate::host_command_wire!(get_file_cache_stats) => resolve_typed::<
            crate::domain::assets::commands::GetFileCacheStatsParams,
        >(ctx, id, args),
        crate::host_command_wire!(list_known_game_directories) => resolve_typed::<
            crate::domain::assets::commands::ListKnownGameDirectoriesParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_audio_data_url) => resolve_typed::<
            crate::domain::assets::commands::LoadAudioDataUrlParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_event_asset) => resolve_typed::<
            crate::domain::assets::commands::LoadEventAssetParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_image_data_url) => resolve_typed::<
            crate::domain::assets::commands::LoadImageDataUrlParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_map_asset) => resolve_typed::<
            crate::domain::assets::commands::LoadMapAssetParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_text_asset) => resolve_typed::<
            crate::domain::assets::commands::LoadTextAssetParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_text_file) => resolve_typed::<
            crate::domain::assets::commands::LoadTextFileParams,
        >(ctx, id, args),
        crate::host_command_wire!(scan_audio_assets) => resolve_typed::<
            crate::domain::assets::commands::ScanAudioAssetsParams,
        >(ctx, id, args),
        crate::host_command_wire!(scan_data_assets) => resolve_typed::<
            crate::domain::assets::commands::ScanDataAssetsParams,
        >(ctx, id, args),
        crate::host_command_wire!(scan_events) => resolve_typed::<
            crate::domain::assets::commands::ScanEventsParams,
        >(ctx, id, args),
        crate::host_command_wire!(scan_image_assets) => resolve_typed::<
            crate::domain::assets::commands::ScanImageAssetsParams,
        >(ctx, id, args),
        crate::host_command_wire!(scan_maps) => resolve_typed::<
            crate::domain::assets::commands::ScanMapsParams,
        >(ctx, id, args),
        crate::host_command_wire!(validate_game_directory) => resolve_typed::<
            crate::domain::assets::commands::ValidateGameDirectoryParams,
        >(ctx, id, args),
        // domain::content_patcher::commands
        crate::host_command_wire!(load_content_patcher_result_asset) => resolve_typed::<
            crate::domain::content_patcher::commands::LoadContentPatcherResultAssetParams,
        >(ctx, id, args),
        // domain::cp_maker::commands
        crate::host_command_wire!(build_cp_maker_map_asset) => resolve_typed::<
            crate::domain::cp_maker::commands::BuildCpMakerMapAssetParams,
        >(ctx, id, args),
        crate::host_command_wire!(copy_cp_maker_draft) => resolve_typed::<
            crate::domain::cp_maker::commands::CopyCpMakerDraftParams,
        >(ctx, id, args),
        crate::host_command_wire!(delete_cp_maker_draft) => resolve_typed::<
            crate::domain::cp_maker::commands::DeleteCpMakerDraftParams,
        >(ctx, id, args),
        crate::host_command_wire!(delete_cp_maker_project_asset) => resolve_typed::<
            crate::domain::cp_maker::commands::DeleteCpMakerProjectAssetParams,
        >(ctx, id, args),
        crate::host_command_wire!(export_cp_maker_pack) => resolve_typed::<
            crate::domain::cp_maker::commands::ExportCpMakerPackParams,
        >(ctx, id, args),
        crate::host_command_wire!(import_cp_maker_pack) => resolve_typed::<
            crate::domain::cp_maker::commands::ImportCpMakerPackParams,
        >(ctx, id, args),
        crate::host_command_wire!(import_cp_maker_project_assets) => resolve_typed::<
            crate::domain::cp_maker::commands::ImportCpMakerProjectAssetsParams,
        >(ctx, id, args),
        crate::host_command_wire!(list_cp_maker_drafts) => resolve_typed::<
            crate::domain::cp_maker::commands::ListCpMakerDraftsParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_cp_maker_draft) => resolve_typed::<
            crate::domain::cp_maker::commands::LoadCpMakerDraftParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_cp_maker_project_map_asset) => resolve_typed::<
            crate::domain::cp_maker::commands::LoadCpMakerProjectMapAssetParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_cp_maker_session) => resolve_typed::<
            crate::domain::cp_maker::commands::LoadCpMakerSessionParams,
        >(ctx, id, args),
        crate::host_command_wire!(read_cp_maker_project_asset) => resolve_typed::<
            crate::domain::cp_maker::commands::ReadCpMakerProjectAssetParams,
        >(ctx, id, args),
        crate::host_command_wire!(rename_cp_maker_project_asset) => resolve_typed::<
            crate::domain::cp_maker::commands::RenameCpMakerProjectAssetParams,
        >(ctx, id, args),
        crate::host_command_wire!(save_cp_maker_draft) => resolve_typed::<
            crate::domain::cp_maker::commands::SaveCpMakerDraftParams,
        >(ctx, id, args),
        crate::host_command_wire!(save_cp_maker_session) => resolve_typed::<
            crate::domain::cp_maker::commands::SaveCpMakerSessionParams,
        >(ctx, id, args),
        crate::host_command_wire!(write_cp_maker_project_asset) => resolve_typed::<
            crate::domain::cp_maker::commands::WriteCpMakerProjectAssetParams,
        >(ctx, id, args),
        crate::host_command_wire!(write_cp_maker_project_assets) => resolve_typed::<
            crate::domain::cp_maker::commands::WriteCpMakerProjectAssetsParams,
        >(ctx, id, args),
        // domain::debug_bridge::commands
        crate::host_command_wire!(get_debug_bridge_mod_state) => resolve_typed::<
            crate::domain::debug_bridge::commands::GetDebugBridgeModStateParams,
        >(ctx, id, args),
        crate::host_command_wire!(get_debug_bridge_status) => resolve_typed::<
            crate::domain::debug_bridge::commands::GetDebugBridgeStatusParams,
        >(ctx, id, args),
        crate::host_command_wire!(install_debug_bridge_mod) => resolve_typed::<
            crate::domain::debug_bridge::commands::InstallDebugBridgeModParams,
        >(ctx, id, args),
        crate::host_command_wire!(send_debug_bridge_command) => resolve_typed::<
            crate::domain::debug_bridge::commands::SendDebugBridgeCommandParams,
        >(ctx, id, args),
        // domain::launcher::commands
        crate::host_command_wire!(cancel_launcher_download) => resolve_typed::<
            crate::domain::launcher::commands::CancelLauncherDownloadParams,
        >(ctx, id, args),
        crate::host_command_wire!(cancel_nexus_sso) => resolve_typed::<
            crate::domain::launcher::commands::CancelNexusSsoParams,
        >(ctx, id, args),
        crate::host_command_wire!(check_launcher_updates) => resolve_typed::<
            crate::domain::launcher::commands::CheckLauncherUpdatesParams,
        >(ctx, id, args),
        crate::host_command_wire!(check_smapi_update) => resolve_typed::<
            crate::domain::launcher::commands::CheckSmapiUpdateParams,
        >(ctx, id, args),
        crate::host_command_wire!(clear_launcher_image_cache) => resolve_typed::<
            crate::domain::launcher::commands::ClearLauncherImageCacheParams,
        >(ctx, id, args),
        crate::host_command_wire!(download_launcher_mod) => resolve_typed::<
            crate::domain::launcher::commands::DownloadLauncherModParams,
        >(ctx, id, args),
        crate::host_command_wire!(find_smapi_installer_downloads) => resolve_typed::<
            crate::domain::launcher::commands::FindSmapiInstallerDownloadsParams,
        >(ctx, id, args),
        crate::host_command_wire!(get_launcher_backup_directory) => resolve_typed::<
            crate::domain::launcher::commands::GetLauncherBackupDirectoryParams,
        >(ctx, id, args),
        crate::host_command_wire!(get_nexus_sso_status) => resolve_typed::<
            crate::domain::launcher::commands::GetNexusSsoStatusParams,
        >(ctx, id, args),
        crate::host_command_wire!(inspect_launcher_archive) => resolve_typed::<
            crate::domain::launcher::commands::InspectLauncherArchiveParams,
        >(ctx, id, args),
        crate::host_command_wire!(install_launcher_archive) => resolve_typed::<
            crate::domain::launcher::commands::InstallLauncherArchiveParams,
        >(ctx, id, args),
        crate::host_command_wire!(install_smapi_update) => resolve_typed::<
            crate::domain::launcher::commands::InstallSmapiUpdateParams,
        >(ctx, id, args),
        crate::host_command_wire!(launch_launcher_game) => resolve_typed::<
            crate::domain::launcher::commands::LaunchLauncherGameParams,
        >(ctx, id, args),
        crate::host_command_wire!(list_launcher_install_backups) => resolve_typed::<
            crate::domain::launcher::commands::ListLauncherInstallBackupsParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_cached_launcher_updates) => resolve_typed::<
            crate::domain::launcher::commands::LoadCachedLauncherUpdatesParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_launcher_download_queue) => resolve_typed::<
            crate::domain::launcher::commands::LoadLauncherDownloadQueueParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_launcher_gmcm_probe_diagnostics) => resolve_typed::<
            crate::domain::launcher::commands::LoadLauncherGmcmProbeDiagnosticsParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_launcher_image_failures) => resolve_typed::<
            crate::domain::launcher::commands::LoadLauncherImageFailuresParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_launcher_library_covers) => resolve_typed::<
            crate::domain::launcher::commands::LoadLauncherLibraryCoversParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_launcher_library_state) => resolve_typed::<
            crate::domain::launcher::commands::LoadLauncherLibraryStateParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_launcher_mod_config) => resolve_typed::<
            crate::domain::launcher::commands::LoadLauncherModConfigParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_launcher_nexus_diagnostics) => resolve_typed::<
            crate::domain::launcher::commands::LoadLauncherNexusDiagnosticsParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_launcher_remote_mod_detail) => resolve_typed::<
            crate::domain::launcher::commands::LoadLauncherRemoteModDetailParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_launcher_runtime_info) => resolve_typed::<
            crate::domain::launcher::commands::LoadLauncherRuntimeInfoParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_launcher_settings) => resolve_typed::<
            crate::domain::launcher::commands::LoadLauncherSettingsParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_launcher_update_changelog) => resolve_typed::<
            crate::domain::launcher::commands::LoadLauncherUpdateChangelogParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_suppressed_launcher_update_mod_ids) => resolve_typed::<
            crate::domain::launcher::commands::LoadSuppressedLauncherUpdateModIdsParams,
        >(ctx, id, args),
        crate::host_command_wire!(open_launcher_path) => resolve_typed::<
            crate::domain::launcher::commands::OpenLauncherPathParams,
        >(ctx, id, args),
        crate::host_command_wire!(open_launcher_url) => resolve_typed::<
            crate::domain::launcher::commands::OpenLauncherUrlParams,
        >(ctx, id, args),
        crate::host_command_wire!(persist_launcher_library_remote_cover) => resolve_typed::<
            crate::domain::launcher::commands::PersistLauncherLibraryRemoteCoverParams,
        >(ctx, id, args),
        crate::host_command_wire!(record_launcher_image_failure) => resolve_typed::<
            crate::domain::launcher::commands::RecordLauncherImageFailureParams,
        >(ctx, id, args),
        crate::host_command_wire!(resolve_cached_launcher_image) => resolve_typed::<
            crate::domain::launcher::commands::ResolveCachedLauncherImageParams,
        >(ctx, id, args),
        crate::host_command_wire!(resolve_launcher_image) => resolve_typed::<
            crate::domain::launcher::commands::ResolveLauncherImageParams,
        >(ctx, id, args),
        crate::host_command_wire!(restart_launcher_nexus_diagnostics) => resolve_typed::<
            crate::domain::launcher::commands::RestartLauncherNexusDiagnosticsParams,
        >(ctx, id, args),
        crate::host_command_wire!(restore_launcher_install_backup) => resolve_typed::<
            crate::domain::launcher::commands::RestoreLauncherInstallBackupParams,
        >(ctx, id, args),
        crate::host_command_wire!(retry_launcher_nexus_diagnostics_route) => resolve_typed::<
            crate::domain::launcher::commands::RetryLauncherNexusDiagnosticsRouteParams,
        >(ctx, id, args),
        crate::host_command_wire!(save_launcher_download_queue) => resolve_typed::<
            crate::domain::launcher::commands::SaveLauncherDownloadQueueParams,
        >(ctx, id, args),
        crate::host_command_wire!(save_launcher_library_state) => resolve_typed::<
            crate::domain::launcher::commands::SaveLauncherLibraryStateParams,
        >(ctx, id, args),
        crate::host_command_wire!(save_launcher_mod_config) => resolve_typed::<
            crate::domain::launcher::commands::SaveLauncherModConfigParams,
        >(ctx, id, args),
        crate::host_command_wire!(save_launcher_settings) => resolve_typed::<
            crate::domain::launcher::commands::SaveLauncherSettingsParams,
        >(ctx, id, args),
        crate::host_command_wire!(scan_launcher_library) => resolve_typed::<
            crate::domain::launcher::commands::ScanLauncherLibraryParams,
        >(ctx, id, args),
        crate::host_command_wire!(search_launcher_catalog) => resolve_typed::<
            crate::domain::launcher::commands::SearchLauncherCatalogParams,
        >(ctx, id, args),
        crate::host_command_wire!(set_launcher_library_cover) => resolve_typed::<
            crate::domain::launcher::commands::SetLauncherLibraryCoverParams,
        >(ctx, id, args),
        crate::host_command_wire!(set_launcher_mod_enabled) => resolve_typed::<
            crate::domain::launcher::commands::SetLauncherModEnabledParams,
        >(ctx, id, args),
        crate::host_command_wire!(set_launcher_nexus_force_offline) => resolve_typed::<
            crate::domain::launcher::commands::SetLauncherNexusForceOfflineParams,
        >(ctx, id, args),
        crate::host_command_wire!(start_nexus_sso) => resolve_typed::<
            crate::domain::launcher::commands::StartNexusSsoParams,
        >(ctx, id, args),
        crate::host_command_wire!(validate_nexus_api_key) => resolve_typed::<
            crate::domain::launcher::commands::ValidateNexusApiKeyParams,
        >(ctx, id, args),
        // domain::localization::commands
        crate::host_command_wire!(acquire_localization_semantic_runtime) => resolve_typed::<
            crate::domain::localization::commands::AcquireLocalizationSemanticRuntimeParams,
        >(ctx, id, args),
        crate::host_command_wire!(cancel_localization_job) => resolve_typed::<
            crate::domain::localization::commands::CancelLocalizationJobParams,
        >(ctx, id, args),
        crate::host_command_wire!(clear_ai_usage) => resolve_typed::<
            crate::domain::localization::commands::ClearAiUsageParams,
        >(ctx, id, args),
        crate::host_command_wire!(copy_translation_memory_entries) => resolve_typed::<
            crate::domain::localization::commands::CopyTranslationMemoryEntriesParams,
        >(ctx, id, args),
        crate::host_command_wire!(create_localization_profile) => resolve_typed::<
            crate::domain::localization::commands::CreateLocalizationProfileParams,
        >(ctx, id, args),
        crate::host_command_wire!(delete_localization_glossary_entries) => resolve_typed::<
            crate::domain::localization::commands::DeleteLocalizationGlossaryEntriesParams,
        >(ctx, id, args),
        crate::host_command_wire!(delete_localization_profile) => resolve_typed::<
            crate::domain::localization::commands::DeleteLocalizationProfileParams,
        >(ctx, id, args),
        crate::host_command_wire!(delete_localization_semantic_model) => resolve_typed::<
            crate::domain::localization::commands::DeleteLocalizationSemanticModelParams,
        >(ctx, id, args),
        crate::host_command_wire!(delete_translation_memory_entries) => resolve_typed::<
            crate::domain::localization::commands::DeleteTranslationMemoryEntriesParams,
        >(ctx, id, args),
        crate::host_command_wire!(download_localization_semantic_model) => resolve_typed::<
            crate::domain::localization::commands::DownloadLocalizationSemanticModelParams,
        >(ctx, id, args),
        crate::host_command_wire!(export_ai_usage) => resolve_typed::<
            crate::domain::localization::commands::ExportAiUsageParams,
        >(ctx, id, args),
        crate::host_command_wire!(export_localization_knowledge) => resolve_typed::<
            crate::domain::localization::commands::ExportLocalizationKnowledgeParams,
        >(ctx, id, args),
        crate::host_command_wire!(import_localization_knowledge) => resolve_typed::<
            crate::domain::localization::commands::ImportLocalizationKnowledgeParams,
        >(ctx, id, args),
        crate::host_command_wire!(initialize_localization_plan) => resolve_typed::<
            crate::domain::localization::commands::InitializeLocalizationPlanParams,
        >(ctx, id, args),
        crate::host_command_wire!(inspect_localization_context) => resolve_typed::<
            crate::domain::localization::commands::InspectLocalizationContextParams,
        >(ctx, id, args),
        crate::host_command_wire!(inspect_localization_semantic_index) => resolve_typed::<
            crate::domain::localization::commands::InspectLocalizationSemanticIndexParams,
        >(ctx, id, args),
        crate::host_command_wire!(inspect_localization_semantic_model) => resolve_typed::<
            crate::domain::localization::commands::InspectLocalizationSemanticModelParams,
        >(ctx, id, args),
        crate::host_command_wire!(inspect_official_localization_index) => resolve_typed::<
            crate::domain::localization::commands::InspectOfficialLocalizationIndexParams,
        >(ctx, id, args),
        crate::host_command_wire!(list_localization_glossary_entries) => resolve_typed::<
            crate::domain::localization::commands::ListLocalizationGlossaryEntriesParams,
        >(ctx, id, args),
        crate::host_command_wire!(list_localization_review_runs) => resolve_typed::<
            crate::domain::localization::commands::ListLocalizationReviewRunsParams,
        >(ctx, id, args),
        crate::host_command_wire!(list_localization_scopes) => resolve_typed::<
            crate::domain::localization::commands::ListLocalizationScopesParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_localization_default_engine) => resolve_typed::<
            crate::domain::localization::commands::LoadLocalizationDefaultEngineParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_localization_review_run) => resolve_typed::<
            crate::domain::localization::commands::LoadLocalizationReviewRunParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_localization_scope) => resolve_typed::<
            crate::domain::localization::commands::LoadLocalizationScopeParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_localization_semantic_settings) => resolve_typed::<
            crate::domain::localization::commands::LoadLocalizationSemanticSettingsParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_localization_style_guide) => resolve_typed::<
            crate::domain::localization::commands::LoadLocalizationStyleGuideParams,
        >(ctx, id, args),
        crate::host_command_wire!(open_localization_semantic_model_directory) => resolve_typed::<
            crate::domain::localization::commands::OpenLocalizationSemanticModelDirectoryParams,
        >(ctx, id, args),
        crate::host_command_wire!(prewarm_localization_corpus) => resolve_typed::<
            crate::domain::localization::commands::PrewarmLocalizationCorpusParams,
        >(ctx, id, args),
        crate::host_command_wire!(probe_localization_semantic_search) => resolve_typed::<
            crate::domain::localization::commands::ProbeLocalizationSemanticSearchParams,
        >(ctx, id, args),
        crate::host_command_wire!(query_ai_usage_records) => resolve_typed::<
            crate::domain::localization::commands::QueryAiUsageRecordsParams,
        >(ctx, id, args),
        crate::host_command_wire!(query_ai_usage_summary) => resolve_typed::<
            crate::domain::localization::commands::QueryAiUsageSummaryParams,
        >(ctx, id, args),
        crate::host_command_wire!(rebuild_localization_semantic_index) => resolve_typed::<
            crate::domain::localization::commands::RebuildLocalizationSemanticIndexParams,
        >(ctx, id, args),
        crate::host_command_wire!(rebuild_official_localization_index) => resolve_typed::<
            crate::domain::localization::commands::RebuildOfficialLocalizationIndexParams,
        >(ctx, id, args),
        crate::host_command_wire!(record_confirmed_translations) => resolve_typed::<
            crate::domain::localization::commands::RecordConfirmedTranslationsParams,
        >(ctx, id, args),
        crate::host_command_wire!(release_localization_semantic_runtime) => resolve_typed::<
            crate::domain::localization::commands::ReleaseLocalizationSemanticRuntimeParams,
        >(ctx, id, args),
        crate::host_command_wire!(remove_localization_profile_binding) => resolve_typed::<
            crate::domain::localization::commands::RemoveLocalizationProfileBindingParams,
        >(ctx, id, args),
        crate::host_command_wire!(rename_localization_profile) => resolve_typed::<
            crate::domain::localization::commands::RenameLocalizationProfileParams,
        >(ctx, id, args),
        crate::host_command_wire!(resolve_localization_scope) => resolve_typed::<
            crate::domain::localization::commands::ResolveLocalizationScopeParams,
        >(ctx, id, args),
        crate::host_command_wire!(review_localization_batch) => resolve_typed::<
            crate::domain::localization::commands::ReviewLocalizationBatchParams,
        >(ctx, id, args),
        crate::host_command_wire!(save_localization_default_engine) => resolve_typed::<
            crate::domain::localization::commands::SaveLocalizationDefaultEngineParams,
        >(ctx, id, args),
        crate::host_command_wire!(save_localization_scope_settings) => resolve_typed::<
            crate::domain::localization::commands::SaveLocalizationScopeSettingsParams,
        >(ctx, id, args),
        crate::host_command_wire!(save_localization_semantic_settings) => resolve_typed::<
            crate::domain::localization::commands::SaveLocalizationSemanticSettingsParams,
        >(ctx, id, args),
        crate::host_command_wire!(save_localization_style_guide) => resolve_typed::<
            crate::domain::localization::commands::SaveLocalizationStyleGuideParams,
        >(ctx, id, args),
        crate::host_command_wire!(search_official_localization) => resolve_typed::<
            crate::domain::localization::commands::SearchOfficialLocalizationParams,
        >(ctx, id, args),
        crate::host_command_wire!(search_translation_memory) => resolve_typed::<
            crate::domain::localization::commands::SearchTranslationMemoryParams,
        >(ctx, id, args),
        crate::host_command_wire!(set_localization_profile_binding) => resolve_typed::<
            crate::domain::localization::commands::SetLocalizationProfileBindingParams,
        >(ctx, id, args),
        crate::host_command_wire!(sync_localization_semantic_index) => resolve_typed::<
            crate::domain::localization::commands::SyncLocalizationSemanticIndexParams,
        >(ctx, id, args),
        crate::host_command_wire!(test_localization_semantic_remote_profile) => resolve_typed::<
            crate::domain::localization::commands::TestLocalizationSemanticRemoteProfileParams,
        >(ctx, id, args),
        crate::host_command_wire!(translate_localization_batch) => resolve_typed::<
            crate::domain::localization::commands::TranslateLocalizationBatchParams,
        >(ctx, id, args),
        crate::host_command_wire!(unload_localization_semantic_runtime) => resolve_typed::<
            crate::domain::localization::commands::UnloadLocalizationSemanticRuntimeParams,
        >(ctx, id, args),
        crate::host_command_wire!(update_localization_review_issues) => resolve_typed::<
            crate::domain::localization::commands::UpdateLocalizationReviewIssuesParams,
        >(ctx, id, args),
        crate::host_command_wire!(upsert_localization_glossary_entries) => resolve_typed::<
            crate::domain::localization::commands::UpsertLocalizationGlossaryEntriesParams,
        >(ctx, id, args),
        crate::host_command_wire!(verify_localization_semantic_model) => resolve_typed::<
            crate::domain::localization::commands::VerifyLocalizationSemanticModelParams,
        >(ctx, id, args),
        // domain::localization::machine_translation::commands
        crate::host_command_wire!(list_machine_translation_languages) => resolve_typed::<
            crate::domain::localization::machine_translation::commands::ListMachineTranslationLanguagesParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_machine_translation_settings) => resolve_typed::<
            crate::domain::localization::machine_translation::commands::LoadMachineTranslationSettingsParams,
        >(ctx, id, args),
        crate::host_command_wire!(save_machine_translation_settings) => resolve_typed::<
            crate::domain::localization::machine_translation::commands::SaveMachineTranslationSettingsParams,
        >(ctx, id, args),
        crate::host_command_wire!(test_machine_translation_profile) => resolve_typed::<
            crate::domain::localization::machine_translation::commands::TestMachineTranslationProfileParams,
        >(ctx, id, args),
        crate::host_command_wire!(translate_machine_translation_batch) => resolve_typed::<
            crate::domain::localization::machine_translation::commands::TranslateMachineTranslationBatchParams,
        >(ctx, id, args),
        // domain::mods::commands
        crate::host_command_wire!(inspect_mod_archive) => resolve_typed::<
            crate::domain::mods::commands::InspectModArchiveParams,
        >(ctx, id, args),
        crate::host_command_wire!(load_mod_project) => resolve_typed::<
            crate::domain::mods::commands::LoadModProjectParams,
        >(ctx, id, args),
        crate::host_command_wire!(save_mod_i18n_files) => resolve_typed::<
            crate::domain::mods::commands::SaveModI18nFilesParams,
        >(ctx, id, args),
        crate::host_command_wire!(scan_mod_asset_index) => resolve_typed::<
            crate::domain::mods::commands::ScanModAssetIndexParams,
        >(ctx, id, args),
        crate::host_command_wire!(scan_mod_projects) => resolve_typed::<
            crate::domain::mods::commands::ScanModProjectsParams,
        >(ctx, id, args),
        // domain::resource_registry::commands
        crate::host_command_wire!(load_resource_registry) => resolve_typed::<
            crate::domain::resource_registry::commands::LoadResourceRegistryParams,
        >(ctx, id, args),
        // domain::saves::commands
        crate::host_command_wire!(scan_default_save_slots) => resolve_typed::<
            crate::domain::saves::commands::ScanDefaultSaveSlotsParams,
        >(ctx, id, args),
        // infrastructure::game_formats::xact::commands
        crate::host_command_wire!(load_xact_audio_data_url) => resolve_typed::<
            crate::infrastructure::game_formats::xact::commands::LoadXactAudioDataUrlParams,
        >(ctx, id, args),
        // support::logging::commands
        crate::host_command_wire!(print_host_runtime_diagnostics) => resolve_typed::<
            crate::support::logging::commands::PrintHostRuntimeDiagnosticsParams,
        >(ctx, id, args),
        crate::host_command_wire!(set_debug_logging_enabled) => resolve_typed::<
            crate::support::logging::commands::SetDebugLoggingEnabledParams,
        >(ctx, id, args),
        crate::host_command_wire!(write_frontend_log) => resolve_typed::<
            crate::support::logging::commands::WriteFrontendLogParams,
        >(ctx, id, args),
        _ => ResolvedCommandOrResponse::Response(HostCommandResponse {
            id,
            ok: false,
            result: None,
            error: Some(json!(format!("Unknown sidecar command: {command}"))),
        }),
    }
}

fn write_json_line<T: Serialize>(stdout: &Arc<Mutex<io::Stdout>>, value: &T) -> Result<(), String> {
    let mut stdout = stdout
        .lock()
        .map_err(|_| "Failed to lock sidecar stdout.".to_string())?;
    serde_json::to_writer(&mut *stdout, value)
        .map_err(|error| format!("Failed to serialize sidecar frame: {error}"))?;
    stdout
        .write_all(b"\n")
        .map_err(|error| format!("Failed to write sidecar frame: {error}"))?;
    stdout
        .flush()
        .map_err(|error| format!("Failed to flush sidecar frame: {error}"))
}

struct StdoutResponseWriter {
    stdout: Arc<Mutex<io::Stdout>>,
}

impl HostCommandResponseWriter for StdoutResponseWriter {
    fn write_response(&self, response: &HostCommandResponse) -> Result<(), String> {
        write_json_line(&self.stdout, response)
    }
}

pub fn run_stdio() -> Result<(), String> {
    let stdout = Arc::new(Mutex::new(io::stdout()));
    let event_stdout = Arc::clone(&stdout);
    let app = AppHandle::sidecar(move |event, payload| {
        write_json_line(
            &event_stdout,
            &RpcEventFrame {
                event: HostEventFrame { event, payload },
            },
        )
    });
    let debug_logging_state = DebugLoggingState::new();
    if let Err(error) = logging::init_sidecar_logging(&debug_logging_state) {
        logging::write_sidecar_fallback_log(
            log::Level::Error,
            targets::SIDECAR,
            LogEvent::new("sidecar.loggingInitFailed")
                .error(format!("{error}"))
                .render(),
        );
    }
    let force_offline = crate::domain::app_ui::load_app_ui_state()
        .map(|state| state.launcher.force_offline)
        .unwrap_or(false);
    domain::nexusmods::diagnostics::prime_nexus_diagnostics_at_startup(&app, force_offline);

    let ctx = DispatchContext {
        app,
        debug_logging_state: debug_logging_state.clone(),
    };
    let scheduler = HostCommandScheduler::new(
        Arc::new(StdoutResponseWriter {
            stdout: Arc::clone(&stdout),
        }),
        Arc::new(HostCommandResourceLocks::new()),
        HostCommandSchedulerConfig::default(),
        debug_logging_state,
    );

    for line in io::stdin().lock().lines() {
        let line = line.map_err(|error| format!("Failed to read sidecar stdin: {error}"))?;
        if line.trim().is_empty() {
            continue;
        }

        let response = match serde_json::from_str::<RpcRequest>(&line) {
            Ok(request) => match resolve_command(&ctx, request) {
                ResolvedCommandOrResponse::Command(command) => {
                    scheduler.submit(command);
                    continue;
                }
                ResolvedCommandOrResponse::Response(response) => response,
            },
            Err(error) => HostCommandResponse {
                id: Value::Null,
                ok: false,
                result: None,
                error: Some(json!(format!("Invalid sidecar JSON-RPC request: {error}"))),
            },
        };

        write_json_line(&stdout, &response)?;
    }

    scheduler.print_diagnostics_summary("sidecar shutdown");
    Ok(())
}

#[cfg(test)]
#[path = "../tests/unit/sidecar/tests.rs"]
mod tests;
