import type { EventCommand } from '@entities/event'
import { createObjectSheetEffect, createStageEffect, type SpecificTemporarySpriteResolution } from '@entities/event'

const UNRESOLVED: SpecificTemporarySpriteResolution | null = null

export function resolveSpecificTemporarySpriteEffectCase5(
  command: EventCommand,
  spriteId: string,
): SpecificTemporarySpriteResolution | null {
  switch (spriteId) {
    case 'WizardPromise':
      return {
        mode: 'append' as const,
        effects: Array.from({ length: 50 }, (_, index) =>
          createStageEffect(command.id, `WizardPromise:${index}`, {
            textureName: 'LooseSprites\\Cursors',
            sourceX: 497,
            sourceY: 1918,
            sourceWidth: 11,
            sourceHeight: 11,
            baseX: (16 + (index % 9)) * 64 + ((index * 11) % 36),
            baseY: (15 + Math.floor(index / 9)) * 64 + ((index * 17) % 36),
            space: 'world',
            animationIntervalMs: 99999,
            animationLength: 1,
            loops: 1,
            scale: 2 + (index % 3) * 0.5,
            motionY: -0.8 - (index % 4) * 0.08,
            alphaFade: 0.01,
            delayBeforeStartMs: index * 40,
            color: '#ffffff',
            layerDepth: 1,
          }),
        ),
      }
    case 'sauceGood':
      return {
        mode: 'append' as const,
        effects: Array.from({ length: 24 }, (_, index) =>
          createStageEffect(command.id, `sauceGood:${index}`, {
            textureName: 'LooseSprites\\Cursors',
            sourceX: 497,
            sourceY: 1918,
            sourceWidth: 11,
            sourceHeight: 11,
            baseX: (64 + (index % 3)) * 64 + ((index * 7) % 20),
            baseY: 16 * 64 + ((index * 13) % 20),
            space: 'world',
            animationIntervalMs: 99999,
            animationLength: 1,
            loops: 1,
            scale: 2.5,
            motionX: ((index % 5) - 2) * 0.15,
            motionY: -0.8 - (index % 3) * 0.1,
            alphaFade: 0.01,
            delayBeforeStartMs: index * 35,
            color: '#ffffff',
            layerDepth: 1,
          }),
        ),
      }
    case 'sebastianFrogHouse':
      return {
        mode: 'append' as const,
        effects: [
          createStageEffect(command.id, 'sebastianFrogHouse:terrarium', {
            textureName: 'LooseSprites\\Cursors',
            sourceX: 641,
            sourceY: 1534,
            sourceWidth: 48,
            sourceHeight: 37,
            baseX: 1 * 64,
            baseY: 6 * 64 - 20,
            space: 'world',
            animationIntervalMs: 5000,
            animationLength: 1,
            loops: 9999,
            scale: 4,
            layerDepth: 0.1,
          }),
          createStageEffect(command.id, 'sebastianFrogHouse:frog', {
            effectNumericId: 777,
            textureName: 'TileSheets\\critters',
            sourceX: 0,
            sourceY: 224,
            sourceWidth: 16,
            sourceHeight: 16,
            baseX: 1 * 64 + 100,
            baseY: 6 * 64 + 8,
            space: 'world',
            animationIntervalMs: 5000,
            animationLength: 1,
            loops: 9999,
            scale: 4,
            flip: true,
            layerDepth: 0.11,
          }),
        ],
      }
    case 'qiCave':
      return {
        mode: 'append' as const,
        effects: [
          createStageEffect(command.id, 'qiCave:portal', {
            textureName: 'LooseSprites\\temporary_sprites_1',
            sourceX: 415,
            sourceY: 216,
            sourceWidth: 96,
            sourceHeight: 89,
            baseX: 2 * 64 + 448,
            baseY: 2 * 64 + 100,
            space: 'world',
            animationIntervalMs: 999999,
            animationLength: 1,
            loops: 99999,
            scale: 4,
            layerDepth: 0.0000001,
          }),
          createStageEffect(command.id, 'qiCave:floor', {
            textureName: 'LooseSprites\\temporary_sprites_1',
            sourceX: 370,
            sourceY: 272,
            sourceWidth: 107,
            sourceHeight: 64,
            baseX: 2 * 64 + 268,
            baseY: 2 * 64 + 324,
            space: 'world',
            animationIntervalMs: 999999,
            animationLength: 1,
            loops: 99999,
            scale: 4,
            layerDepth: 0.00000011,
          }),
          createObjectSheetEffect(command.id, 'qiCave:item', 803, {
            effectNumericId: 803,
            baseX: 13 * 64 + 4,
            baseY: 7 * 64 + 36,
            space: 'world',
            animationIntervalMs: 999999,
            animationLength: 1,
            loops: 99999,
            scale: 4,
            layerDepth: 0.0000021,
          }),
          ...[
            { x: 8, y: 6, interval: 100, depth: 0.0000022 },
            { x: 5, y: 7, interval: 90, depth: 0.0000023 },
            { x: 7, y: 10, interval: 120, depth: 1 },
            { x: 15, y: 7, interval: 80, depth: 0.0000024 },
            { x: 12, y: 11, interval: 100, depth: 0.0000025 },
            { x: 16, y: 10, interval: 105, depth: 0.0000026 },
            { x: 3, y: 9, interval: 85, depth: 0.0000027 },
          ].map((entry, index) =>
            createStageEffect(command.id, `qiCave:pillar:${index}`, {
              effectNumericId: 11,
              textureName: 'LooseSprites\\temporary_sprites_1',
              sourceX: 432,
              sourceY: 171,
              sourceWidth: 16,
              sourceHeight: 30,
              baseX: entry.x * 64,
              baseY: entry.y * 64,
              space: 'world',
              animationIntervalMs: entry.interval,
              animationLength: 5,
              loops: 99999,
              pingPong: true,
              scale: 4,
              layerDepth: entry.depth,
            }),
          ),
        ],
      }
    case 'robot':
      return {
        mode: 'append' as const,
        effects: [
          createStageEffect(command.id, 'robot:core', {
            textureName: 'Characters\\robot',
            sourceX: 35,
            sourceY: 42,
            sourceWidth: 35,
            sourceHeight: 42,
            baseX: 13 * 64,
            baseY: 27 * 64 - 32,
            space: 'world',
            animationIntervalMs: 50,
            animationLength: 1,
            loops: 9999,
            scale: 4,
            layerDepth: 0.98,
            accelerationY: -0.01,
          }),
          ...Array.from({ length: 64 }, (_, index) =>
            createStageEffect(command.id, `robot:spark:${index}`, {
              textureName: 'TileSheets\\animations',
              sourceX: (index % 4) * 64,
              sourceY: 320,
              sourceWidth: 64,
              sourceHeight: 64,
              baseX: 13 * 64 + ((index * 17) % 96),
              baseY: 136,
              space: 'screen',
              animationIntervalMs: 9999,
              animationLength: 1,
              loops: 1,
              scale: 1,
              alpha: 0.75,
              motionX: ((index % 9) - 4) / (index + 20),
              motionY: 0.25 + index / 100,
              delayBeforeStartMs: index * 10,
              layerDepth: 1,
            }),
          ),
        ],
      }
    case 'maruTrapdoor':
      return {
        mode: 'append' as const,
        effects: [
          createStageEffect(command.id, 'maruTrapdoor:open', {
            textureName: 'LooseSprites\\Cursors',
            sourceX: 640,
            sourceY: 1632,
            sourceWidth: 16,
            sourceHeight: 32,
            baseX: 1 * 64,
            baseY: 5 * 64,
            space: 'world',
            animationIntervalMs: 150,
            animationLength: 4,
            loops: 1,
            scale: 4,
            layerDepth: 1,
          }),
          createStageEffect(command.id, 'maruTrapdoor:shadow', {
            textureName: 'LooseSprites\\Cursors',
            sourceX: 688,
            sourceY: 1632,
            sourceWidth: 16,
            sourceHeight: 32,
            baseX: 1 * 64,
            baseY: 5 * 64,
            space: 'world',
            animationIntervalMs: 99999,
            animationLength: 1,
            loops: 1,
            scale: 4,
            delayBeforeStartMs: 500,
            layerDepth: 0.99,
          }),
        ],
      }
    case 'shaneCliffs':
      return {
        mode: 'append' as const,
        effects: [
          createStageEffect(command.id, 'shaneCliffs:body', {
            effectNumericId: 999,
            textureName: 'LooseSprites\\Cursors',
            sourceX: 533,
            sourceY: 1864,
            sourceWidth: 19,
            sourceHeight: 27,
            baseX: 83 * 64,
            baseY: 98 * 64,
            space: 'world',
            animationIntervalMs: 99999,
            animationLength: 1,
            loops: 99999,
            scale: 4,
            layerDepth: 0.01,
          }),
          createStageEffect(command.id, 'shaneCliffs:shadow', {
            textureName: 'LooseSprites\\Cursors',
            sourceX: 552,
            sourceY: 1862,
            sourceWidth: 31,
            sourceHeight: 21,
            baseX: 83 * 64 - 16,
            baseY: 98 * 64,
            space: 'world',
            animationIntervalMs: 99999,
            animationLength: 1,
            loops: 99999,
            scale: 4,
            layerDepth: 0.0001,
          }),
          createStageEffect(command.id, 'shaneCliffs:propA', {
            effectNumericId: 999,
            textureName: 'LooseSprites\\Cursors',
            sourceX: 549,
            sourceY: 1891,
            sourceWidth: 19,
            sourceHeight: 12,
            baseX: 84 * 64,
            baseY: 99 * 64,
            space: 'world',
            animationIntervalMs: 99999,
            animationLength: 1,
            loops: 99999,
            scale: 4,
            layerDepth: 0.01,
          }),
          createStageEffect(command.id, 'shaneCliffs:propB', {
            effectNumericId: 999,
            textureName: 'LooseSprites\\Cursors',
            sourceX: 549,
            sourceY: 1891,
            sourceWidth: 19,
            sourceHeight: 12,
            baseX: 82 * 64,
            baseY: 98 * 64,
            space: 'world',
            animationIntervalMs: 99999,
            animationLength: 1,
            loops: 99999,
            scale: 4,
            layerDepth: 0.01,
          }),
          createStageEffect(command.id, 'shaneCliffs:can', {
            textureName: 'LooseSprites\\Cursors',
            sourceX: 542,
            sourceY: 1893,
            sourceWidth: 4,
            sourceHeight: 6,
            baseX: 83 * 64 - 32,
            baseY: 99 * 64 + 16,
            space: 'world',
            animationIntervalMs: 99999,
            animationLength: 1,
            loops: 99999,
            scale: 4,
            layerDepth: 1,
          }),
        ],
      }
    case 'candleBoat':
      return {
        mode: 'append' as const,
        effects: [
          createStageEffect(command.id, 'candleBoat', {
            effectNumericId: 1,
            textureName: 'Maps\\Festivals',
            sourceX: 240,
            sourceY: 112,
            sourceWidth: 16,
            sourceHeight: 32,
            baseX: 22 * 64,
            baseY: 36 * 64,
            space: 'world',
            animationIntervalMs: 1000,
            animationLength: 2,
            loops: 99999,
            scale: 4,
            layerDepth: 1,
          }),
        ],
      }
    case 'candleBoatMove':
      return { effects: [], mode: 'update-candle-boat' as const, effectNumericId: 1 }
    case 'abbyvideoscreen':
      return {
        mode: 'append' as const,
        effects: [
          createStageEffect(command.id, 'abbyvideoscreen', {
            textureName: 'LooseSprites\\Cursors',
            sourceX: 167,
            sourceY: 1714,
            sourceWidth: 19,
            sourceHeight: 14,
            baseX: 2 * 64 + 28,
            baseY: 3 * 64 + 48,
            space: 'world',
            animationIntervalMs: 100,
            animationLength: 3,
            loops: 9999,
            scale: 4,
            layerDepth: 0.0002,
          }),
        ],
      }
    case 'islandFishSplash':
      return {
        mode: 'append' as const,
        effects: [
          createStageEffect(command.id, 'islandFishSplash', {
            effectNumericId: 9999,
            textureName: 'Maps\\springobjects',
            sourceX: 336,
            sourceY: 544,
            sourceWidth: 16,
            sourceHeight: 16,
            baseX: 81 * 64,
            baseY: 92 * 64,
            space: 'world',
            animationIntervalMs: 100000,
            animationLength: 1,
            loops: 1,
            flip: true,
            scale: 4,
            layerDepth: 0.99,
            motionX: -2,
            motionY: -8,
            accelerationY: 0.2,
            rotationChange: -0.02,
          }),
        ],
      }
    case 'sebastianGarage':
      return {
        mode: 'append' as const,
        effects: [
          createStageEffect(command.id, 'sebastianGarage', {
            textureName: 'LooseSprites\\Cursors',
            sourceX: 276,
            sourceY: 1843,
            sourceWidth: 48,
            sourceHeight: 42,
            baseX: 17 * 64,
            baseY: 23 * 64 + 8,
            space: 'world',
            animationIntervalMs: 9999,
            animationLength: 1,
            loops: 999,
            scale: 4,
            layerDepth: 0.1472,
          }),
        ],
      }
    case 'sunroom':
      return {
        mode: 'append' as const,
        effects: [
          createStageEffect(command.id, 'sunroom', {
            effectNumericId: 996,
            textureName: 'LooseSprites\\temporary_sprites_1',
            sourceX: 304,
            sourceY: 486,
            sourceWidth: 24,
            sourceHeight: 26,
            baseX: 4 * 64 + 32,
            baseY: 8 * 64 - 32,
            space: 'world',
            animationIntervalMs: 99999,
            animationLength: 1,
            loops: 997,
            scale: 4,
            layerDepth: 0.0512,
          }),
        ],
      }
    case 'shakeBush':
      return { effects: [], mode: 'update-shake' as const, effectNumericId: 777, shakeIntensity: 1 }
    case 'parrotHutSquawk':
      return { effects: [], mode: 'update-parrot-perch-squawk' as const, effectNumericId: 999 }
    case 'frogJump':
      return { effects: [], mode: 'update-frog-jump' as const, effectNumericId: 777 }
    case 'raccoonCircle':
      return {
        mode: 'append' as const,
        effects: [
          createStageEffect(command.id, 'raccoonCircle:raccoon', {
            effectNumericId: 9786,
            textureName: 'Characters\\raccoon',
            sourceX: 0,
            sourceY: 0,
            sourceWidth: 32,
            sourceHeight: 32,
            baseX: 54.5 * 64,
            baseY: 7 * 64,
            space: 'world',
            animationIntervalMs: 148,
            animationLength: 8,
            loops: 999,
            scale: 4,
            layerDepth: 0.051840004,
          }),
          createStageEffect(command.id, 'raccoonCircle:mrs', {
            effectNumericId: 9785,
            textureName: 'Characters\\mrs_raccoon',
            sourceX: 0,
            sourceY: 0,
            sourceWidth: 32,
            sourceHeight: 32,
            baseX: 56.5 * 64,
            baseY: 7 * 64,
            space: 'world',
            animationIntervalMs: 148,
            animationLength: 8,
            loops: 999,
            scale: 4,
            layerDepth: 0.0512,
          }),
          createStageEffect(command.id, 'raccoonCircle:cutout', {
            effectNumericId: 997799,
            textureName: 'LooseSprites\\raccoon_circle_cutout',
            sourceX: 0,
            sourceY: 0,
            sourceWidth: 263,
            sourceHeight: 263,
            baseX: 2750,
            baseY: 0,
            space: 'screen',
            animationIntervalMs: 99999,
            animationLength: 1,
            loops: 1,
            scale: 4,
            layerDepth: 1,
            alpha: 0.88,
          }),
        ],
      }
    case 'raccoondance1':
      return { effects: [], mode: 'update-raccoon-dance' as const, effectNumericId: 9786 }
    case 'raccoondance2':
      return { effects: [], mode: 'update-raccoon-dance' as const, effectNumericId: 9785 }
    case 'raccoonCircle2':
      return {
        mode: 'append' as const,
        effects: [
          createStageEffect(command.id, 'raccoonCircle2', {
            effectNumericId: 997797,
            textureName: 'LooseSprites\\raccoon_circle_cutout',
            sourceX: 0,
            sourceY: 0,
            sourceWidth: 263,
            sourceHeight: 263,
            baseX: 3080,
            baseY: 0,
            space: 'screen',
            animationIntervalMs: 297,
            animationLength: 3,
            loops: 99999,
            scale: 4,
            alpha: 0.01,
            alphaFade: -0.003,
            layerDepth: 0.8,
          }),
        ],
      }
    case 'raccoonbutterflies':
      return {
        mode: 'append' as const,
        effects: [
          { x: 52.5 * 64 - 131.5 * 4, y: 60 * 4, sx: 128, sy: 336, px: 32, py: 8, loopX: 2800, loopY: 3800 },
          { x: 56.5 * 64 - 131.5 * 4, y: 0, sx: 192, sy: 336, px: 32, py: 4, loopX: 2600, loopY: 2900 },
          { x: 53.5 * 64 + 263 * 4, y: 24 * 4, sx: 128, sy: 288, px: 32, py: 6, loopX: 3000, loopY: 3100 },
          { x: 52.5 * 64 + 131.5 * 4, y: 220 * 4, sx: 192, sy: 288, px: 32, py: 12, loopX: 2400, loopY: 2800 },
          { x: 52.5 * 64 + 186.5 * 4, y: 150 * 4, sx: 64, sy: 288, px: 32, py: 4, loopX: 3400, loopY: 3200 },
          { x: 52.5 * 64 + 211.5 * 4, y: 180 * 4, sx: 128, sy: 96, px: 32, py: 4, loopX: 3500, loopY: 2700 },
          { x: 52.5 * 64 - 126.5 * 4, y: -120 * 4, sx: 192, sy: 112, px: 16, py: 4, loopX: 2500, loopY: 3300 },
          { x: 49.5 * 64 - 126.5 * 4, y: -100 * 4, sx: 128, sy: 288, px: 16, py: 4, loopX: 2200, loopY: 3400 },
        ].map((entry, index) =>
          createStageEffect(command.id, `raccoonbutterflies:${index}`, {
            effectNumericId: 997799,
            textureName: 'TileSheets\\critters',
            sourceX: entry.sx,
            sourceY: entry.sy,
            sourceWidth: 16,
            sourceHeight: 16,
            baseX: entry.x,
            baseY: entry.y,
            space: 'screen',
            animationIntervalMs: 148,
            animationLength: 4,
            loops: 99999,
            pingPong: true,
            scale: 4,
            xPeriodic: true,
            xPeriodicLoopTimeMs: entry.loopX,
            xPeriodicRange: entry.px,
            yPeriodic: true,
            yPeriodicLoopTimeMs: entry.loopY,
            yPeriodicRange: entry.py,
            alpha: 0.01,
            alphaFade: -0.01,
            layerDepth: 1,
          }),
        ),
      }
    case 'raccoonSong':
      return {
        mode: 'append' as const,
        effects: [
          createStageEffect(command.id, 'raccoonSong:noteA', {
            textureName: 'LooseSprites\\Cursors_1_6',
            sourceX: 279,
            sourceY: 55,
            sourceWidth: 12,
            sourceHeight: 15,
            baseX: 3706 - 26,
            baseY: 340 - 48,
            space: 'screen',
            animationIntervalMs: 297,
            animationLength: 8,
            loops: 999,
            scale: 4,
            layerDepth: 0.044809997,
          }),
          createStageEffect(command.id, 'raccoonSong:noteB', {
            textureName: 'LooseSprites\\Cursors_1_6',
            sourceX: 374,
            sourceY: 55,
            sourceWidth: 12,
            sourceHeight: 15,
            baseX: 54 * 64,
            baseY: 4 * 64 - 16,
            space: 'world',
            animationIntervalMs: 297,
            animationLength: 8,
            loops: 999,
            flip: true,
            scale: 4,
            delayBeforeStartMs: 297,
            layerDepth: 0.044809997,
          }),
          ...Array.from({ length: 8 }, (_, index) => [
            createStageEffect(command.id, `raccoonSong:petal:${index}`, {
              textureName: 'LooseSprites\\Cursors_1_6',
              sourceX: 304,
              sourceY: 397,
              sourceWidth: 11,
              sourceHeight: 11,
              baseX: 3706 + 56,
              baseY: 340 - 48,
              space: 'screen',
              animationIntervalMs: 49,
              animationLength: 12,
              loops: 1,
              scale: 4,
              motionX: 1,
              accelerationY: 0.001,
              rotationChange: ((index % 5) - 2) / 100,
              color: '#ffc8c8',
              delayBeforeStartMs: 2376 * index,
              layerDepth: 0.05057,
            }),
            createStageEffect(command.id, `raccoonSong:flash:${index}`, {
              textureName: 'LooseSprites\\Cursors_1_6',
              sourceX: 455,
              sourceY: 414,
              sourceWidth: 14,
              sourceHeight: 17,
              baseX: 3706 + 28,
              baseY: 340 - 48,
              space: 'screen',
              animationIntervalMs: 2376,
              animationLength: 1,
              loops: 999,
              scale: 4,
              alphaFade: 0.02,
              delayBeforeStartMs: 2376 * index,
              layerDepth: 0.051209997,
            }),
          ]).flat(),
        ],
      }
    case 'georgeLeekGift':
      return {
        mode: 'append' as const,
        effects: [
          createStageEffect(command.id, 'georgeLeekGift', {
            effectNumericId: 999,
            textureName: 'LooseSprites\\Cursors',
            sourceX: 288,
            sourceY: 1231,
            sourceWidth: 16,
            sourceHeight: 16,
            baseX: 17 * 64,
            baseY: 19 * 64,
            space: 'world',
            animationIntervalMs: 100,
            animationLength: 6,
            loops: 1,
            holdLastFrame: true,
            scale: 4,
            layerDepth: 0.01,
          }),
        ],
      }
    default:
      return UNRESOLVED
  }
}
