export {
  DEPRECATED_ATTACHMENT_KINDS,
  MAIL_TOOL_TYPES,
  parseMailAttachmentBody,
  serializeMailAttachment,
  type MailAttachment,
  type MailAttachmentKind,
  type MailItemPair,
} from './attachments'
export {
  getLetterBgFrame,
  getLetterBgSheetGeometry,
  LETTER_BG_ASSET_NAME,
  LETTER_BG_FRAME_HEIGHT,
  LETTER_BG_FRAME_WIDTH,
  MAIL_TEXT_COLOR_IDS,
  MAX_VANILLA_LETTER_BG_INDEX,
  resolveLetterInkColorId,
  VANILLA_LETTER_BACKGROUNDS,
  type LetterBgSheetGeometry,
  type MailTextColorId,
  type VanillaLetterBackground,
  type VanillaLetterBackgroundId,
} from './catalogs'
export {
  buildMailDeliveryGroups,
  classifyMailDelivery,
  MAIL_DELIVERY_GROUP_ORDER,
  type MailDeliveryGroup,
  type MailDeliveryGroupId,
  type MailLetterSummary,
} from './deliveryGroups'
export {
  getVanillaBackgroundIndex,
  mailDraftFromString,
  mailDraftToString,
  parseMailBodyTokens,
  parseMailString,
  serializeLetterBackground,
  serializeMailString,
  type MailDraftAttachment,
  type MailLetterBackgroundRef,
  type MailLetterDraft,
  type MailStringSegment,
  type ParsedMailString,
} from './mailString'
export {
  buildAddMailAction,
  MAIL_DELIVERY_TYPES,
  MAIL_TRIGGER_EVENTS,
  MAIL_TRIGGER_TARGETS,
  parseAddMailAction,
  tokenizeActionString,
  triggerDraftFromEntry,
  triggerDraftToEntry,
  type MailDeliveryType,
  type MailTriggerDraft,
  type MailTriggerTarget,
  type ParsedAddMailAction,
} from './triggerEntries'
export {
  MOD_ID_PREFIX,
  summarizeIssues,
  validateMailLetter,
  type MailLetterValidationInput,
  type MailValidationCode,
  type MailValidationIssue,
  type MailValidationSeverity,
} from './validation'
