import { localeBundles } from '@locales'
import type { EditorCopy, LocaleCode, ModWorkspaceCopy, ThemeMode, WorkspaceMode } from '@locales/api'
import { createDefaultContentPatcherSimulationContext } from '../workspaces/mod'
import type { BuildWorkspacePanelsOptions } from '../model/workspace-panels/buildWorkspacePanels'
import type { GameDirectoryInfo } from '@entities/game/api'
import type { WorkspaceStatus } from '@entities/map'

const EMPTY_WORKSPACE_STATUS: WorkspaceStatus = {
  tone: 'idle',
  message: '',
}

type CreatePreviewPanelDefaultsOptions = {
  copy: EditorCopy
  modWorkspaceCopy: ModWorkspaceCopy
  locale: LocaleCode
  workspaceMode: WorkspaceMode
  directoryInfo: GameDirectoryInfo | null
  theme: ThemeMode
  accentColor: string
  heavyWorkspaceReady: boolean
}

/** Provides inert panel options so preview runtimes only override their active workspace fields. */
export function createPreviewPanelDefaults({
  copy,
  modWorkspaceCopy,
  locale,
  workspaceMode,
  directoryInfo,
  theme,
  accentColor,
  heavyWorkspaceReady,
}: CreatePreviewPanelDefaultsOptions): BuildWorkspacePanelsOptions {
  const moduleBlueprint =
    workspaceMode === 'map' || workspaceMode === 'events' || workspaceMode === 'mods' || workspaceMode === 'mod-i18n'
      ? undefined
      : copy.moduleBlueprints[workspaceMode]

  return {
    copy,
    locale,
    workspaceMode,
    gameRootPath: directoryInfo?.rootPath ?? null,
    directoryInfo,
    mapAssets: [],
    filteredAssets: [],
    mapBrowserSourceMode: 'original',
    onMapBrowserSourceModeChange: () => {},
    modMapGroups: [],
    activeModMapSelectionId: null,
    activeMapModSources: [],
    activeMapId: null,
    activeAssetName: undefined,
    assetFilter: '',
    onAssetFilterChange: () => {},
    onOpenAsset: () => {},
    onOpenModAsset: () => {},
    workspaceTabs: [],
    activeTabId: '',
    onSelectWorkspaceTab: () => {},
    onCloseWorkspaceTab: () => {},
    onReorderWorkspaceTabs: () => {},
    mapDocument: null,
    worldAtlasViews: [],
    activeWorldAtlasViewId: null,
    onSelectWorldAtlasView: () => {},
    onOpenAtlasTarget: () => {},
    theme,
    accentColor,
    visibleLayerIds: [],
    onToggleLayer: () => {},
    onShowAllLayers: () => {},
    onHideAllLayers: () => {},
    visibleObjectGroupIds: [],
    onToggleObjectGroup: () => {},
    onShowAllObjectGroups: () => {},
    onHideAllObjectGroups: () => {},
    focusedObjectTarget: null,
    showGameWorldAdditions: false,
    onToggleGameWorldAdditions: () => {},
    worldOverlaySprites: [],
    worldOverlayTextureAssets: {},
    onFocusObject: () => {},
    onHoverChange: () => {},
    workspaceStatus: EMPTY_WORKSPACE_STATUS,
    moduleBlueprint,
    eventAssets: [],
    filteredEventAssets: [],
    eventBrowserSourceMode: 'original',
    onEventBrowserSourceModeChange: () => {},
    modEventGroups: [],
    activeModEventSelectionId: null,
    activeEventModSources: [],
    activeEventAssetId: null,
    eventAssetFilter: '',
    onEventAssetFilterChange: () => {},
    onOpenEventAsset: () => {},
    onOpenModEventAsset: () => {},
    parsedEventAsset: null,
    selectedEventKey: null,
    selectedEvent: null,
    selectedTimelineEntryId: '',
    currentEventCommandId: null,
    eventStatusMessage: '',
    onSelectEvent: () => {},
    onSelectTimelineEntry: () => {},
    onActivateTimelineEntry: () => {},
    onPlaybackCommandChange: () => {},
    onStageSeekReady: () => () => {},
    activePlayerAppearanceProfile: null,
    onOpenPlayerAppearanceWindow: () => {},
    characters: [],
    filteredCharacters: [],
    characterBrowserSourceMode: 'original',
    onCharacterBrowserSourceModeChange: () => {},
    modCharacterGroups: [],
    activeModCharacterSelectionId: null,
    activeCharacterModSources: [],
    activeCharacterId: null,
    activeCharacter: null,
    activeCharacterVariant: null,
    characterFilter: '',
    characterStatusMessage: '',
    activeCharacterAssetState: {} as never,
    onCharacterFilterChange: () => {},
    onSelectCharacter: () => {},
    onSelectModCharacter: () => {},
    onSelectCharacterVariant: () => {},
    constructibleGroups: [],
    filteredConstructibleGroups: [],
    worldBuildings: [],
    filteredWorldBuildings: [],
    buildingBrowserSourceMode: 'original',
    onBuildingBrowserSourceModeChange: () => {},
    modBuildingGroups: [],
    activeModBuildingSelectionId: null,
    activeBuildingModSources: [],
    activeBuildingId: null,
    activeBuilding: null,
    activeUpgradeChain: [],
    buildingFilter: '',
    buildingStatusMessage: '',
    activeBuildingTextureState: null,
    activeBuildingChainTextureStates: {},
    activeBuildingIndoorMapDocument: null,
    activeBuildingIndoorMapPath: null,
    activeBuildingIndoorMapMessage: '',
    activeBuildingExteriorMapDocument: null,
    activeBuildingExteriorMapPath: null,
    activeBuildingExteriorMapMessage: '',
    activeBuildingExteriorFocusPoint: null,
    buildingSpringObjectsState: {} as never,
    onBuildingFilterChange: () => {},
    onSelectBuilding: () => {},
    onSelectModBuilding: () => {},
    items: [],
    filteredItems: [],
    itemBrowserSourceMode: 'original',
    onItemBrowserSourceModeChange: () => {},
    modItemGroups: [],
    activeModItemSelectionId: null,
    activeItemModSources: [],
    activeItemId: null,
    activeItem: null,
    itemLookup: new Map(),
    itemFilter: '',
    itemStatusMessage: '',
    itemTextureStatesByAssetName: {},
    ensureItemTextureAssetStates: () => {},
    onItemFilterChange: () => {},
    onSelectItem: () => {},
    onSelectModItem: () => {},
    heavyWorkspaceReady,
    modWorkspaceCopy,
    modI18nCopy: localeBundles[locale].modI18n,
    modPluginDefinition: null,
    modProjects: [],
    filteredModProjects: [],
    activeProjectPath: null,
    activeProject: null,
    modFilter: '',
    contentPatcherOnly: true,
    compatibleOnly: true,
    onModFilterChange: () => {},
    onContentPatcherOnlyChange: () => {},
    onCompatibleOnlyChange: () => {},
    onSelectModProject: () => {},
    onImportModProject: () => {},
    onRefreshModProjects: () => {},
    activeModProjectDetail: null,
    modManifestEditor: { text: '', value: null, error: null },
    modContentEditor: { text: '', value: null, error: null },
    modContentSummary: {
      format: null,
      changeCount: 0,
      includeCount: 0,
      dynamicTokenCount: 0,
      configKeys: [],
      patches: [],
    },
    modDiagnostics: [],
    activeModPatchId: null,
    onSelectModPatch: () => {},
    activeModPatch: null,
    modPatchWhenError: null,
    modHasUnsavedChanges: false,
    modCanPersist: false,
    modStatusMessage: '',
    modLastSaveResult: null,
    contentPatcherSnapshot: null,
    contentPatcherSimulation: null,
    contentPatcherResultAsset: null,
    contentPatcherResultLoading: false,
    contentPatcherResultError: null,
    simulationContext: createDefaultContentPatcherSimulationContext(),
    modI18nFiles: [],
    modI18nSourceLocale: 'default',
    modI18nTargetLocale: 'zh-CN',
    modI18nQuery: '',
    modI18nStatusFilter: 'all',
    onModI18nSourceLocaleChange: () => {},
    onModI18nTargetLocaleChange: () => {},
    onModI18nQueryChange: () => {},
    onModI18nStatusFilterChange: () => {},
    onModI18nFilesChange: () => {},
    navigatorMode: 'patches',
    selectedTargetPath: null,
    onNavigatorModeChange: () => {},
    scaleUpEditor: null,
    onModManifestFieldChange: () => {},
    onModManifestTextChange: () => {},
    onModContentTextChange: () => {},
    onAddModPatch: () => {},
    onRemoveModPatch: () => {},
    onModPatchFieldChange: () => {},
    onModPatchWhenChange: () => {},
    onSaveModProject: () => {},
    onExportModProject: () => {},
    onSimulationContextChange: () => {},
    onSelectTarget: () => {},
  }
}
