export {
  buildObjectDisplayIndex,
  hydrateBuildingMaterials,
  loadBuildingImageState,
  loadBuildingMaterialOptions,
  loadBuildingWorkspaceEntries,
  loadChainTextureStates,
  loadVanillaBuildingRecords,
  localizeBuildingEntries,
  resolveLocalizedText,
  type BuildingMaterialOption,
  type BuildingObjectDisplay,
} from './api/buildingAssets'
export { buildAbsoluteSpriteLayerStyle, getResolvedSourceRect } from './lib/buildingSprites'
export { useBuildingAuthoringHandoff } from './model/authoringHandoff'
export {
  addBuildingEntry,
  BUILDER_SUGGESTIONS,
  BUILDING_FIELD_ORDER,
  BUILDING_ID_TOKEN_PREFIX,
  BUILDING_TYPE_SUGGESTIONS,
  createMinimalBuildingEntry,
  displayNameFromBuildingId,
  findBuildingTexturePatchState,
  INDOOR_MAP_TYPE_SUGGESTIONS,
  OCCUPANT_TYPE_SUGGESTIONS,
  validateBuildingFootprint,
  type AddBuildingEntryResult,
  type BuildingAssetPatchInput,
  type BuildingAssetPatchState,
  type BuildingDataFields,
  type BuildingFootprint,
  type BuildingFootprintError,
  type BuildingMaterialFields,
  type BuildingPlacementTileFields,
  type BuildingPoint,
  type BuildingRectangle,
  type BuildingSkinFields,
} from './model/buildingFields'
export {
  buildGameContentPath,
  buildMapPathLabel,
  BUILDINGS_DATA_ASSET_PATH,
  createBuildingEntriesFromRecords,
  createBuildingEntryIndex,
  createConstructibleBuildingGroups,
  getBuildingTexturePath,
  normalizeIndoorMapAssetName,
  parseBuildingPoint,
  parseBuildingRectangle,
  parseQualifiedObjectId,
  type BuildingMaterialEntry,
  type BuildingPlacementTileEntry,
  type BuildingSkinEntry,
  type BuildingSourceKind,
  type BuildingTextureAssetState,
  type BuildingWorkspaceEntry,
  type ConstructibleBuildingGroup,
  type ResolvedBuildingPoint,
  type ResolvedBuildingRectangle,
  type WorldBuildingEntrance,
} from './model/buildingIndex'
export { BUILDING_DATA_ASSET_ID, BUILDING_DATA_SCHEMA } from './model/buildingSchema'
export { validateBuildingEntries, type BuildingValidationContext } from './model/validation'
export { BuildingSpritePreview, type BuildingSpriteGeometry, type BuildingSpritePreviewProps } from './ui/BuildingSpritePreview'
