import { vi } from 'vite-plus/test'
import type { CpMakerPort } from '@features/cp-maker/model/cpMakerPort'

export function createMockCpMakerPort(overrides: Partial<CpMakerPort> = {}): CpMakerPort {
  return {
    listDrafts: vi.fn().mockResolvedValue([]),
    loadDraft: vi.fn().mockResolvedValue({
      draftStorageKey: 'draft-1',
      projectMetadata: {
        projectName: '',
        projectDescription: '',
        projectAuthor: '',
        projectVersion: '',
        projectUniqueId: '',
        gameRootPath: null,
        contentPackForUniqueId: '',
      },
      overlayTargets: [],
      configSchemaDraft: {},
      serializedChangeRegistry: {},
      dynamicTokens: [],
      customLocations: [],
      aliasTokenNames: {},
      eventSourceSnapshotsByTarget: {},
      lastDraftSavedAt: null,
      lastExportedAt: null,
      lastExportPath: null,
      lastExportFingerprint: null,
    }),
    saveDraft: vi.fn().mockResolvedValue({
      draftStorageKey: 'draft-1',
      projectMetadata: {
        projectName: '',
        projectDescription: '',
        projectAuthor: '',
        projectVersion: '',
        projectUniqueId: '',
        gameRootPath: null,
        contentPackForUniqueId: '',
      },
      overlayTargets: [],
      configSchemaDraft: {},
      serializedChangeRegistry: {},
      dynamicTokens: [],
      customLocations: [],
      aliasTokenNames: {},
      eventSourceSnapshotsByTarget: {},
      lastDraftSavedAt: null,
      lastExportedAt: null,
      lastExportPath: null,
      lastExportFingerprint: null,
    }),
    deleteDraft: vi.fn().mockResolvedValue(undefined),
    copyDraft: vi.fn().mockResolvedValue({
      draftStorageKey: 'draft-1-copy',
      projectMetadata: {
        projectName: '',
        projectDescription: '',
        projectAuthor: '',
        projectVersion: '',
        projectUniqueId: '',
        gameRootPath: null,
        contentPackForUniqueId: '',
      },
      overlayTargets: [],
      configSchemaDraft: {},
      serializedChangeRegistry: {},
      dynamicTokens: [],
      customLocations: [],
      aliasTokenNames: {},
      eventSourceSnapshotsByTarget: {},
      lastDraftSavedAt: null,
      lastExportedAt: null,
      lastExportPath: null,
      lastExportFingerprint: null,
    }),
    importPack: vi.fn().mockResolvedValue({
      draftStorageKey: 'draft-1-import',
      projectMetadata: {
        projectName: '',
        projectDescription: '',
        projectAuthor: '',
        projectVersion: '',
        projectUniqueId: '',
        gameRootPath: null,
        contentPackForUniqueId: '',
      },
      overlayTargets: [],
      configSchemaDraft: {},
      serializedChangeRegistry: {},
      dynamicTokens: [],
      customLocations: [],
      aliasTokenNames: {},
      eventSourceSnapshotsByTarget: {},
      lastDraftSavedAt: null,
      lastExportedAt: null,
      lastExportPath: null,
      lastExportFingerprint: null,
    }),
    exportPack: vi.fn().mockResolvedValue({
      output_path: '',
      manifest_path: '',
      content_path: '',
      virtual_asset_paths: [],
    }),
    chooseDirectory: vi.fn().mockResolvedValue(null),
    scanMaps: vi.fn().mockResolvedValue([]),
    scanEvents: vi.fn().mockResolvedValue([]),
    scanModProjects: vi.fn().mockResolvedValue([]),
    loadMapAsset: vi.fn().mockResolvedValue({
      name: '',
      format: '',
      absolutePath: '',
      relativePath: '',
      content: '',
    }),
    loadTextAsset: vi.fn().mockResolvedValue({
      absolutePath: '',
      relativePath: '',
      content: '',
    }),
    loadImageDataUrl: vi.fn().mockResolvedValue(''),
    ...overrides,
  }
}
