import { vi } from 'vitest'
import type { LauncherPort } from '@features/launcher/model/launcherPort'

export function createMockLauncherPort(overrides: Partial<LauncherPort> = {}): LauncherPort {
  const defaultSettings = {
    gamePath: null,
    modsPath: null,
    downloadPath: null,
    nexusApiKey: null,
    nexusCookie: null,
    autoInstallDownloads: false,
    keepDownloadedArchives: false,
    autoCheckModUpdates: true,
    disablePublicHtmlRoute: false,
  }

  const unimplemented = (method: keyof LauncherPort) =>
    vi.fn(() => {
      throw new Error(`LauncherPort.${method} was called without an explicit test override.`)
    })

  return {
    loadSettings: vi.fn().mockResolvedValue({
      ...defaultSettings,
    }),
    saveSettings: vi.fn().mockImplementation(async (request) => ({
      ...defaultSettings,
      ...request,
    })),
    scanLibrary: unimplemented('scanLibrary'),
    loadLibraryState: vi.fn().mockResolvedValue({
      storageFolders: [],
      hiddenModKeys: [],
      packPresets: [],
      currentPackId: null,
      scopeMode: 'all' as const,
    }),
    saveLibraryState: unimplemented('saveLibraryState'),
    loadLibraryCovers: unimplemented('loadLibraryCovers'),
    setLibraryCover: unimplemented('setLibraryCover'),
    persistLibraryRemoteCover: unimplemented('persistLibraryRemoteCover'),
    loadDownloadQueue: vi.fn().mockResolvedValue({ items: [] }),
    saveDownloadQueue: unimplemented('saveDownloadQueue'),
    searchCatalog: unimplemented('searchCatalog'),
    loadRemoteModDetail: unimplemented('loadRemoteModDetail'),
    loadUpdateChangelog: unimplemented('loadUpdateChangelog'),
    loadNexusDiagnostics: vi.fn().mockResolvedValue({ routes: [] }),
    restartNexusDiagnostics: vi.fn().mockResolvedValue({ routes: [] }),
    retryNexusDiagnosticsRoute: vi.fn().mockResolvedValue({ routes: [] }),
    setNexusForceOffline: vi.fn().mockResolvedValue({ routes: [] }),
    resolveImage: unimplemented('resolveImage'),
    loadCachedUpdates: vi.fn().mockResolvedValue(null),
    loadSuppressedUpdateModIds: vi.fn().mockResolvedValue({ modsPath: '', modIds: [] }),
    checkUpdates: unimplemented('checkUpdates'),
    listenToUpdateProgress: vi.fn().mockResolvedValue(() => {}),
    downloadMod: unimplemented('downloadMod'),
    installArchive: unimplemented('installArchive'),
    listInstallBackups: unimplemented('listInstallBackups'),
    restoreInstallBackup: unimplemented('restoreInstallBackup'),
    inspectArchive: unimplemented('inspectArchive'),
    launchGame: unimplemented('launchGame'),
    openPath: unimplemented('openPath'),
    openUrl: unimplemented('openUrl'),
    clearLibraryReadCaches: vi.fn(),
    chooseArchiveFile: unimplemented('chooseArchiveFile'),
    chooseImageFile: unimplemented('chooseImageFile'),
    getBackupDirectory: unimplemented('getBackupDirectory'),
    setModEnabled: unimplemented('setModEnabled'),
    chooseDirectory: unimplemented('chooseDirectory'),
    detectDefaultGameDirectory: vi.fn().mockResolvedValue(null),
    toDesktopAssetUrl: vi.fn().mockReturnValue(''),
    openPublicHtmlVerification: vi.fn().mockImplementation(async (request: { targetUrl: string; reason: string }) => ({
      state: 'opening' as const,
      targetUrl: request.targetUrl,
      reason: request.reason as 'diagnostics' | 'remote-mod-detail' | 'remote-mod-images' | 'remote-mod-files',
      disablePublicHtmlRoute: false,
      lastVerifiedAtMs: null,
      message: null,
    })),
    loadPublicHtmlVerificationState: vi.fn().mockResolvedValue({
      state: 'idle' as const,
      targetUrl: null,
      reason: null,
      disablePublicHtmlRoute: false,
      lastVerifiedAtMs: null,
      message: null,
    }),
    listenToPublicHtmlVerificationState: vi.fn().mockResolvedValue(() => {}),
    signalPublicHtmlVerificationOpened: vi.fn().mockResolvedValue({
      state: 'waitingForUser' as const,
      targetUrl: null,
      reason: 'diagnostics' as const,
      disablePublicHtmlRoute: false,
      lastVerifiedAtMs: null,
      message: null,
    }),
    submitPublicHtmlVerificationCookie: vi.fn().mockImplementation(async () => ({
      state: 'verified' as const,
      targetUrl: null,
      reason: 'diagnostics' as const,
      disablePublicHtmlRoute: false,
      lastVerifiedAtMs: Date.now(),
      message: 'Verification successful.',
    })),
    cancelPublicHtmlVerification: vi.fn().mockResolvedValue({
      state: 'cancelled' as const,
      targetUrl: null,
      reason: null,
      disablePublicHtmlRoute: false,
      lastVerifiedAtMs: null,
      message: null,
    }),
    refreshPublicHtmlVerification: vi.fn().mockResolvedValue(undefined),
    checkPublicHtmlVerification: vi.fn().mockResolvedValue({
      state: 'waitingForUser' as const,
      targetUrl: null,
      reason: null,
      disablePublicHtmlRoute: false,
      lastVerifiedAtMs: null,
      message: null,
    }),
    closePublicHtmlVerification: vi.fn().mockResolvedValue(undefined),
    clearPublicHtmlVerificationSession: vi.fn().mockResolvedValue(undefined),
    subscribeUpdates: vi.fn().mockReturnValue(() => {}),
    ...overrides,
  }
}
