// 命令参数选项列表 — 为选择器提供可枚举值

// ─── NPC / 角色 ─────────────────────────────────────────────────────────

export const NPC_OPTIONS = [
  'Abigail',
  'Alex',
  'Caroline',
  'Clint',
  'Demetrius',
  'Dwarf',
  'Elliott',
  'Emily',
  'Evelyn',
  'George',
  'Gil',
  'Gunther',
  'Gus',
  'Haley',
  'Harvey',
  'Jas',
  'Jodi',
  'Kent',
  'Krobus',
  'Leah',
  'Leo',
  'Lewis',
  'Linus',
  'Marnie',
  'Maru',
  'Morris',
  'Pam',
  'Penny',
  'Pierre',
  'Robin',
  'Sam',
  'Sandy',
  'Sebastian',
  'Shane',
  'Vincent',
  'Willy',
  'Wizard',
]

export const ACTOR_OPTIONS = [...NPC_OPTIONS, 'farmer', 'farmer2', 'farmer3', 'farmer4', 'spouse', 'player']

// ─── 地图 ────────────────────────────────────────────────────────────────

export const MAP_OPTIONS = [
  'Farm',
  'FarmHouse',
  'Greenhouse',
  'Cellar',
  'Town',
  'Beach',
  'Mountain',
  'Forest',
  'BusStop',
  'Railroad',
  'Woods',
  'Sewer',
  'BugLand',
  'WizardHouse',
  'WizardHouseBasement',
  'BathHouse_Entry',
  'BathHouse_MensLocker',
  'BathHouse_WomensLocker',
  'BathHouse_Pool',
  'Desert',
  'Club',
  'SandyHouse',
  'SkullCave',
  'Mine',
  'Mine20',
  'Mine60',
  'Mine100',
  'Hospital',
  'HarveyRoom',
  'SeedShop',
  'Blacksmith',
  'Saloon',
  'Trailer',
  'Trailer_Big',
  'JoshHouse',
  'ScienceHouse',
  'SebastianRoom',
  'HaleyHouse',
  'SamHouse',
  'ElliottCabin',
  'LeahHouse',
  'AnimalShop',
  'ArchaeologyHouse',
  'ManorHouse',
  'CommunityCenter',
  'AdventureGuild',
  'JojaMart',
  'FishShop',
  'AbandonedJojaMart',
  'Sunroom',
  'IslandSouth',
  'IslandNorth',
  'IslandWest',
  'IslandEast',
  'IslandHut',
  'IslandShrine',
  'Caldera',
  'CaptainRoom',
  'VolcanoDungeon0',
  'VolcanoDungeon1',
  'VolcanoDungeon2',
  'VolcanoDungeon3',
  'VolcanoDungeon4',
  'VolcanoDungeon5',
]

// ─── 音乐 ────────────────────────────────────────────────────────────────

export const MUSIC_OPTIONS = [
  'wavy',
  'woodsTheme',
  'saloon1',
  'spring1',
  'spring2',
  'spring3',
  'summer1',
  'summer2',
  'summer3',
  'fall1',
  'fall2',
  'fall3',
  'winter1',
  'winter2',
  'winter3',
  'libraryTheme',
  'marnieShop',
  'Submarine_Song',
  'night_market',
  'caldera',
  'IslandMusic',
  'fieldoffice',
  '50s',
  'christmas_theme',
  'movieTheater',
  'movie_wedding',
  'ragtime',
  'wizardSong',
  'tribal',
  'spaceMusic',
  'moonlightJellies',
  'starshoot',
  'tickTock',
  'showrunner_sound',
  '-desert',
  'elliotsPiano',
  'sampractice',
  'shaneTheme',
  'MarlonsTheme',
  'AbigailFlute',
  'heavy',
  'Cavern',
  'Crystal Bells',
  'Cloth',
  'XOR',
  'sappypiano',
  'Kindling in the Snow…',
  'jaunty',
]

// ─── 音效 ────────────────────────────────────────────────────────────────

export const SOUND_OPTIONS = [
  'coin',
  'money',
  'moneyDial',
  'Select',
  'backpackIN',
  'backpackOUT',
  'fishSlap',
  'button1',
  'bigSelect',
  'breathin',
  'breathout',
  'jingle1',
  'Cowboy_Secret',
  'cowboy_monsterhit',
  'cowboy_gunload',
  'cowboy_powerup',
  'cowboy_explosion',
  'pickaxe',
  'axe',
  'hoeHit',
  'hammer',
  'swordswipe',
  'daggerswipe',
  'clubsmash',
  'clubswipe',
  'shadowpeep',
  'ghost',
  'secret1',
  'discoverMineral',
  'newArtifact',
  'newRecord',
  'reward',
  'getNewSpecialItem',
  'harvest',
  'toolSwap',
  'drumkit0',
  'drumkit1',
  'drumkit2',
  'drumkit3',
  'drumkit4',
  'drumkit5',
  'drumkit6',
  'purchase',
  'purchaseClick',
  'cancel',
  'eat',
  'gulp',
  'crafting',
  'leafrustle',
  'openBox',
  'openChest',
  'doorClose',
  'doorOpen',
  'bubbles',
  'dwop',
  'stairsdown',
  'warp',
  'fallDown',
  'thudStep',
  'crunch',
  'stoneCrack',
  'slosh',
  'furnace',
  'throw',
  'shwip',
  'boulderCrack',
  'skeletonHit',
  'skeletonStep',
  'rockGolemHit',
  'rockGolemRockThrow',
  'dustMeep',
  'junimoMeep1',
  'sprayCan',
  'fireball',
  'debuffSpell',
  'batScreech',
  'batFlap',
  'serpentAttack',
  'serpentHit',
  'bugLevelUp',
  'dirtyHit',
  'wand',
  'healSound',
  'debuffHit',
  'coldSpell',
  'yoba',
  'explosion',
  'thunder_small',
  'thunder',
  'thunder_medium',
  'thunder_big',
  'thunder_far',
  'rain',
  'wind',
  'sinewave',
  'tinyWhip',
  'purchaseRepeat',
  'grassyStep',
  'snowyStep',
  'thudStep',
  'stoneStep',
  'WoodWhack',
  'boop',
  'hitEnemy',
  'criticalHit',
  'wind',
  'dog_pant',
  'dog_bark',
  'cat',
  'Duck',
  'parrot_squawk',
  'Parrot_squawk',
  'parrot',
  'owl',
  'cackling',
  'grunt',
  'croak',
  'Puffer',
  'Puffer_rocket',
  'Bobber',
  'fishEscape',
  'fishHit',
  'pullItemFromWater',
  'Milking',
  'Shear',
  'Duggy',
  'DuggyHit',
  'DuggyDie',
  'Slime',
  'slimedead',
  'SlimeHit',
  ' slimeHurt',
  'LavaDrip',
  'SkeletonDie',
  'Ghost',
  'MagicalRiff',
  'newRecipe',
  'newArtifact',
  'cut',
  'whistle',
  'ui_select',
  'ui_move_selection',
  'ui_qm_release',
  'ui_qm_press',
  'ui_qm_tick',
  'ui_trashcan',
  'ui_trashcan_shake',
  'dropItemInWater',
  'dwop',
  'junimoMeep1',
  'fairy',
]

// ─── 表情 ────────────────────────────────────────────────────────────────

export const EMOTE_OPTIONS = [
  { value: '0', label: '0 思考' },
  { value: '1', label: '1 问号' },
  { value: '2', label: '2 感叹号' },
  { value: '3', label: '3 愤怒' },
  { value: '4', label: '4 睡觉' },
  { value: '5', label: '5 爱心' },
  { value: '6', label: '6 骷髅' },
  { value: '7', label: '7 笑脸' },
  { value: '8', label: '8 心碎' },
  { value: '9', label: '9 哭泣' },
  { value: '10', label: '10 尴尬' },
  { value: '11', label: '11 惊讶' },
  { value: '12', label: '12 星星' },
  { value: '13', label: '13 音符' },
  { value: '14', label: '14 生气' },
  { value: '15', label: '15 开心' },
  { value: '16', label: '16 金币' },
  { value: '17', label: '17 礼物' },
  { value: '18', label: '18 书本' },
  { value: '19', label: '19 灯泡' },
  { value: '20', label: '20 晕眩' },
  { value: '21', label: '21 雪花' },
  { value: '22', label: '22 火焰' },
  { value: '23', label: '23 水滴' },
  { value: '24', label: '24 云朵' },
  { value: '25', label: '25 树叶' },
  { value: '26', label: '26 月亮' },
  { value: '27', label: '27 太阳' },
  { value: '28', label: '28 闪电' },
  { value: '29', label: '29 彩虹' },
  { value: '30', label: '30 奖杯' },
  { value: '31', label: '31 皇冠' },
]

// ─── 常用物品 / 对象 ─────────────────────────────────────────────────────

export const ITEM_OPTIONS = [
  { value: '(O)24', label: 'Parsnip (O)24' },
  { value: '(O)60', label: 'Emerald (O)60' },
  { value: '(O)62', label: 'Aquamarine (O)62' },
  { value: '(O)72', label: 'Diamond (O)72' },
  { value: '(O)128', label: 'Pufferfish (O)128' },
  { value: '(O)176', label: 'Egg (O)176' },
  { value: '(O)194', label: 'Fried Egg (O)194' },
  { value: '(O)216', label: 'Bread (O)216' },
  { value: '(O)268', label: 'Starfruit (O)268' },
  { value: '(O)334', label: 'Copper Bar (O)334' },
  { value: '(O)335', label: 'Iron Bar (O)335' },
  { value: '(O)336', label: 'Gold Bar (O)336' },
  { value: '(O)337', label: 'Iridium Bar (O)337' },
  { value: '(O)348', label: 'Driftwood (O)348' },
  { value: '(O)372', label: 'Clam (O)372' },
  { value: '(O)388', label: 'Wood (O)388' },
  { value: '(O)390', label: 'Stone (O)390' },
  { value: '(O)428', label: 'Cloth (O)428' },
  { value: '(O)434', label: 'Stardrop (O)434' },
  { value: '(O)709', label: 'Hardwood (O)709' },
  { value: '(O)787', label: 'Battery Pack (O)787' },
]

// ─── 速度 ────────────────────────────────────────────────────────────────

export const SPEED_OPTIONS = ['1', '2', '3', '4', '5', '6']

// ─── 方向 ────────────────────────────────────────────────────────────────

export const DIRECTION_OPTIONS = ['0', '1', '2', '3']

// ─── 淡出速度 ────────────────────────────────────────────────────────────

export const FADE_SPEED_OPTIONS = ['slow', 'medium', 'fast']

// ─── 结束模式 ────────────────────────────────────────────────────────────

export const END_MODE_OPTIONS = ['dialogue', 'none']

// ─── 动画帧 ──────────────────────────────────────────────────────────────

export const ANIMATION_FRAME_OPTIONS = Array.from({ length: 32 }, (_, i) => String(i))

// ─── 天气/季节相关 ───────────────────────────────────────────────────────

export const SEASON_OPTIONS = ['spring', 'summer', 'fall', 'winter']

// ─── 眼睛状态 ────────────────────────────────────────────────────────────

export const EYES_OPTIONS = [
  { value: '0', label: '0 正常' },
  { value: '1', label: '1 闭眼' },
  { value: '2', label: '2 悲伤' },
  { value: '3', label: '3 震惊' },
  { value: '4', label: '4 睡觉' },
]

// ─── 玩家动画 ────────────────────────────────────────────────────────────

export const FARMER_ANIMATION_OPTIONS = ['0', '1', '2', '3', '4', '5', '6', '7']

// ─── 图层 ────────────────────────────────────────────────────────────────

export const LAYER_OPTIONS = ['Back', 'Buildings', 'Front', 'AlwaysFront']
