import {
  buildingAuthoringRegistration,
  buildingBrowserRegistration,
  characterAuthoringRegistration,
  characterBrowserRegistration,
  devResourceBrowserRegistration,
  dialogueEditorRegistration,
  eventAuthoringRegistration,
  eventBrowserRegistration,
  gameDebuggerRegistration,
  i18nGeneratorRegistration,
  aiLocalizationRegistration,
  itemAuthoringRegistration,
  itemBrowserRegistration,
  mailEditorRegistration,
  mapAuthoringRegistration,
  mapBrowserRegistration,
  modBrowserRegistration,
  modTranslationRegistration,
  projectContentRegistration,
  projectDashboardRegistration,
  projectSettingsRegistration,
  projectTranslationRegistration,
  scheduleEditorRegistration,
} from '@pages/workbench/module-registrations'
import { createAppRegistry } from './registry'

export const appRegistry = createAppRegistry({
  workbenchModules: [
    mapBrowserRegistration,
    eventBrowserRegistration,
    characterBrowserRegistration,
    buildingBrowserRegistration,
    itemBrowserRegistration,
    modBrowserRegistration,
    modTranslationRegistration,
    i18nGeneratorRegistration,
    aiLocalizationRegistration,
    gameDebuggerRegistration,
    projectDashboardRegistration,
    projectContentRegistration,
    projectSettingsRegistration,
    mapAuthoringRegistration,
    eventAuthoringRegistration,
    characterAuthoringRegistration,
    dialogueEditorRegistration,
    scheduleEditorRegistration,
    mailEditorRegistration,
    buildingAuthoringRegistration,
    itemAuthoringRegistration,
    projectTranslationRegistration,
    ...(import.meta.env.DEV ? [devResourceBrowserRegistration] : []),
  ],
})
