/**
 * Catalog of the Content Patcher targets that ship with Stardew Valley 1.6.
 *
 * The lists mirror the vanilla `Content/` tree (`Data/`, `Data/Events/`,
 * `Characters/Dialogue/`, `Characters/schedules/`, `Maps/`, `Portraits/`,
 * `TileSheets/`, `LooseSprites/`), so a target offered by the workbench always
 * resolves in game. Spelling follows the shipped file names — Content Patcher
 * matches case-insensitively, but the authored `Target` should read the way the
 * game writes it (`Data/mail`, `Data/hats`, `Maps/Trailer_big`).
 *
 * Only assets a mod realistically patches are listed; the picker always keeps a
 * free-text field for everything else, including modded targets.
 */

/** NPCs with a `Characters/Dialogue/<name>` asset. */
const DIALOGUE_NPCS: readonly string[] = [
  'Abigail',
  'Alex',
  'Caroline',
  'Clint',
  'Demetrius',
  'Dwarf',
  'Elliott',
  'Emily',
  'Evelyn',
  'George',
  'Gil',
  'Gus',
  'Haley',
  'Harvey',
  'Jas',
  'Jodi',
  'Kent',
  'Krobus',
  'Leah',
  'Leo',
  'LeoMainland',
  'Lewis',
  'Linus',
  'Marnie',
  'Maru',
  'Mister Qi',
  'Pam',
  'Penny',
  'Pierre',
  'Robin',
  'Sam',
  'Sandy',
  'Sebastian',
  'Shane',
  'Vincent',
  'Willy',
  'Wizard',
]

/** Marriage candidates, whose post-wedding lines live in a second dialogue asset. */
const MARRIAGE_CANDIDATES: readonly string[] = [
  'Abigail',
  'Alex',
  'Elliott',
  'Emily',
  'Haley',
  'Harvey',
  'Krobus',
  'Leah',
  'Maru',
  'Penny',
  'Sam',
  'Sebastian',
  'Shane',
]

/** NPCs with a `Characters/schedules/<name>` asset. */
const SCHEDULE_NPCS: readonly string[] = [
  'Abigail',
  'Alex',
  'Caroline',
  'Clint',
  'Demetrius',
  'Elliott',
  'Emily',
  'Evelyn',
  'George',
  'Gus',
  'Haley',
  'Harvey',
  'Jas',
  'Jodi',
  'Kent',
  'Leah',
  'Leo',
  'LeoMainland',
  'Lewis',
  'Linus',
  'Marnie',
  'Maru',
  'Pam',
  'Penny',
  'Pierre',
  'Robin',
  'Sam',
  'Sandy',
  'Sebastian',
  'Shane',
  'Vincent',
  'Willy',
]

/** Locations with a `Data/Events/<location>` asset. */
const EVENT_LOCATIONS: readonly string[] = [
  'Town',
  'Farm',
  'FarmHouse',
  'Beach',
  'Mountain',
  'Forest',
  'Backwoods',
  'BusStop',
  'Railroad',
  'SeedShop',
  'Saloon',
  'Hospital',
  'ArchaeologyHouse',
  'AnimalShop',
  'FishShop',
  'ScienceHouse',
  'ManorHouse',
  'JoshHouse',
  'HaleyHouse',
  'SamHouse',
  'LeahHouse',
  'ElliottHouse',
  'SandyHouse',
  'HarveyRoom',
  'SebastianRoom',
  'Sunroom',
  'Trailer',
  'Trailer_Big',
  'Tent',
  'Sewer',
  'Mine',
  'Woods',
  'WizardHouse',
  'CommunityCenter',
  'AbandonedJojaMart',
  'BoatTunnel',
  'BathHouse_Pool',
  'DesertFestival',
  'IslandSouth',
  'IslandNorth',
  'IslandWest',
  'IslandHut',
  'IslandFarmHouse',
  'QiNutRoom',
]

/**
 * `EditData` targets: the flat `Data/*` assets plus the per-NPC and
 * per-location data files that live outside `Data/`.
 */
export const VANILLA_DATA_TARGETS: readonly string[] = [
  // Items and crafting
  'Data/Objects',
  'Data/BigCraftables',
  'Data/Crops',
  'Data/FruitTrees',
  'Data/WildTrees',
  'Data/GiantCrops',
  'Data/Fish',
  'Data/FishPondData',
  'Data/AquariumFish',
  'Data/CookingRecipes',
  'Data/CraftingRecipes',
  'Data/TailoringRecipes',
  'Data/Furniture',
  'Data/Boots',
  'Data/Pants',
  'Data/Shirts',
  'Data/hats',
  'Data/Trinkets',
  'Data/Weapons',
  'Data/Tools',
  'Data/Fences',
  'Data/FloorsAndPaths',
  'Data/AdditionalWallpaperFlooring',
  'Data/Mannequins',
  'Data/Machines',
  'Data/Powers',
  'Data/Buffs',
  // NPCs and dialogue
  'Data/Characters',
  'Data/NPCGiftTastes',
  'Data/EngagementDialogue',
  'Data/ExtraDialogue',
  'Data/Weddings',
  'Data/Pets',
  'Data/FarmAnimals',
  'Data/Monsters',
  'Data/HairData',
  'Data/MakeoverOutfits',
  ...DIALOGUE_NPCS.map((npc) => `Characters/Dialogue/${npc}`),
  'Characters/Dialogue/MarriageDialogue',
  ...MARRIAGE_CANDIDATES.map((npc) => `Characters/Dialogue/MarriageDialogue${npc}`),
  ...SCHEDULE_NPCS.map((npc) => `Characters/schedules/${npc}`),
  // World, buildings and locations
  'Data/Locations',
  'Data/LocationContexts',
  'Data/Buildings',
  'Data/Minecarts',
  'Data/WorldMap',
  'Data/AdditionalFarms',
  'Data/HomeRenovations',
  'Data/GarbageCans',
  'Data/ChairTiles',
  'Data/PaintData',
  // Events and scripted content
  ...EVENT_LOCATIONS.map((location) => `Data/Events/${location}`),
  'Data/TriggerActions',
  'Data/PassiveFestivals',
  'Data/Movies',
  'Data/MoviesReactions',
  'Data/Concessions',
  'Data/ConcessionTastes',
  // Progression and economy
  'Data/Shops',
  'Data/Quests',
  'Data/SpecialOrders',
  'Data/MonsterSlayerQuests',
  'Data/Bundles',
  'Data/RandomBundles',
  'Data/MuseumRewards',
  'Data/Achievements',
  'Data/LostItemsShop',
  // Notifications and flavour text
  'Data/mail',
  'Data/SecretNotes',
  'Data/IncomingPhoneCalls',
  'Data/TV/TipChannel',
  'Data/TV/CookingChannel',
  'Data/JukeboxTracks',
  'Data/AudioChanges',
  'Data/animationDescriptions',
  'Data/AdditionalLanguages',
]

/** `EditImage` targets: portraits, character sprites and the shared sprite sheets. */
export const VANILLA_IMAGE_TARGETS: readonly string[] = [
  ...MARRIAGE_CANDIDATES.map((npc) => `Portraits/${npc}`),
  ...MARRIAGE_CANDIDATES.map((npc) => `Characters/${npc}`),
  'Maps/springobjects',
  'TileSheets/Craftables',
  'TileSheets/Objects_2',
  'TileSheets/crops',
  'TileSheets/fruitTrees',
  'TileSheets/furniture',
  'TileSheets/tools',
  'TileSheets/weapons',
  'TileSheets/ChairTiles',
  'TileSheets/Mannequins',
  'TileSheets/BuffsIcons',
  'TileSheets/animations',
  'TileSheets/critters',
  'TileSheets/emotes',
  'LooseSprites/Cursors',
  'LooseSprites/Cursors_1_6',
  'LooseSprites/Giftbox',
  'LooseSprites/JunimoNote',
  'LooseSprites/map',
]

/** `EditMap` targets: the shipped location maps. */
export const VANILLA_MAP_TARGETS: readonly string[] = [
  'Maps/Town',
  'Maps/Farm',
  'Maps/FarmHouse',
  'Maps/FarmCave',
  'Maps/Cellar',
  'Maps/Greenhouse',
  'Maps/Beach',
  'Maps/Mountain',
  'Maps/Forest',
  'Maps/Backwoods',
  'Maps/BusStop',
  'Maps/Railroad',
  'Maps/Desert',
  'Maps/SeedShop',
  'Maps/Saloon',
  'Maps/Hospital',
  'Maps/ArchaeologyHouse',
  'Maps/Blacksmith',
  'Maps/AnimalShop',
  'Maps/FishShop',
  'Maps/ScienceHouse',
  'Maps/ManorHouse',
  'Maps/JoshHouse',
  'Maps/HaleyHouse',
  'Maps/SamHouse',
  'Maps/LeahHouse',
  'Maps/ElliottHouse',
  'Maps/SandyHouse',
  'Maps/Trailer',
  'Maps/Trailer_big',
  'Maps/Sewer',
  'Maps/WizardHouse',
  'Maps/AdventureGuild',
  'Maps/CommunityCenter',
  'Maps/JojaMart',
  'Maps/MovieTheater',
  'Maps/Mine',
  'Maps/SkullCave',
  'Maps/Woods',
  'Maps/Barn',
  'Maps/Coop',
  'Maps/Shed',
  'Maps/SlimeHutch',
  'Maps/Island_S',
  'Maps/Island_N',
  'Maps/Island_W',
  'Maps/Island_E',
  'Maps/IslandFarmHouse',
]
