// lib/events/commandTemplates.ts
// 命令默认模板 — 用于快速插入新命令

export const COMMAND_TEMPLATES: Record<string, string> = {
  speak: 'speak Abigail "Hello!"',
  splitSpeak: 'splitSpeak Abigail "Hello...#there!"',
  message: 'message "A message appears..."',
  pause: 'pause 1000',
  move: 'move Abigail 0 1 0 2 2',
  warp: 'warp Abigail 10 15 2',
  emote: 'emote Abigail 8',
  faceDirection: 'faceDirection Abigail 2',
  playMusic: 'playMusic wavy',
  playSound: 'playSound coin',
  stopMusic: 'stopMusic',
  stopSound: 'stopSound',
  viewport: 'viewport 10 10',
  changeLocation: 'changeLocation Town',
  globalFade: 'globalFade',
  globalFadeToClear: 'globalFadeToClear',
  fade: 'fade',
  question: 'question "Choose one?"',
  quickQuestion: 'quickQuestion "Quick choice?"',
  catQuestion: 'catQuestion',
  cave: 'cave',
  fork: 'fork',
  switchEvent: 'switchEvent newEvent',
  end: 'end',
  beginSimultaneousCommand: 'beginSimultaneousCommand',
  endSimultaneousCommand: 'endSimultaneousCommand',
  jump: 'jump Abigail',
  shake: 'shake 500',
  screenFlash: 'screenFlash',
  addItem: 'addItem "Object name"',
  removeItem: 'removeItem "Object name"',
  money: 'money 100',
  friendship: 'friendship Abigail 250',
  animate: 'animate Abigail true',
  stopAnimation: 'stopAnimation Abigail',
  showFrame: 'showFrame Abigail 0',
  speed: 'speed Abigail 4',
  advancedMove: 'advancedMove Abigail false 0 1',
  warpFarmers: 'warpFarmers 10 15',
  addObject: 'addObject 10 15 "Object name"',
  removeObject: 'removeObject 10 15',
  addProp: 'addProp 10 15 "Prop name"',
  addBigProp: 'addBigProp 10 15 "Prop name"',
  addFloorProp: 'addFloorProp 10 15 "Prop name"',
  addTemporaryActor: 'addTemporaryActor "Actor" 16 32 10 15 2',
  removeSprite: 'removeSprite Abigail',
  changeSprite: 'changeSprite Abigail "NewSprite"',
  changePortrait: 'changePortrait Abigail "NewPortrait"',
  textAboveHead: 'textAboveHead Abigail "Hello!"',
  glow: 'glow Abigail',
  stopGlowing: 'stopGlowing Abigail',
  setRunning: 'setRunning Abigail true',
  stopRunning: 'stopRunning Abigail',
  startJittering: 'startJittering Abigail',
  stopJittering: 'stopJittering Abigail',
  ignoreMovementAnimation: 'ignoreMovementAnimation Abigail',
  ignoreCollisions: 'ignoreCollisions Abigail',
  farmerAnimation: 'farmerAnimation 0',
  farmerEat: 'farmerEat "Object name"',
  itemAboveHead: 'itemAboveHead "Object name"',
  mail: 'mail "LetterId"',
  mailReceived: 'mailReceived "LetterId"',
  mailToday: 'mailToday "LetterId"',
  addQuest: 'addQuest "QuestId"',
  removeQuest: 'removeQuest "QuestId"',
  addSpecialOrder: 'addSpecialOrder "OrderId"',
  removeSpecialOrder: 'removeSpecialOrder "OrderId"',
  addCookingRecipe: 'addCookingRecipe "Recipe name"',
  addCraftingRecipe: 'addCraftingRecipe "Recipe name"',
  addConversationTopic: 'addConversationTopic "TopicId" 7',
  addLantern: 'addLantern 10 15',
  cutscene: 'cutscene "CutsceneId"',
  doAction: 'doAction 10 15',
  proceedPosition: 'proceedPosition',
  playerControl: 'playerControl',
  skippable: 'skippable',
  halt: 'halt',
  eyes: 'eyes Abigail 0',
  changeName: 'changeName Abigail "NewName"',
  changeMapTile: 'changeMapTile "Back" 10 15 "TileSheet" 0',
  changeToTemporaryMap: 'changeToTemporaryMap "MapName"',
  changeYSourceRectOffset: 'changeYSourceRectOffset Abigail 0',
  attachCharacterToTempSprite: 'attachCharacterToTempSprite Abigail',
  awardFestivalPrize: 'awardFestivalPrize',
  broadcastEvent: 'broadcastEvent',
  characterSelect: 'characterSelect',
  dump: 'dump',
  elliotbooktalk: 'elliotbooktalk',
  eventSeen: 'eventSeen',
  extendSourceRect: 'extendSourceRect Abigail 0 0',
  grandpaCandles: 'grandpaCandles',
  grandpaEvaluation: 'grandpaEvaluation',
  grandpaEvaluation2: 'grandpaEvaluation2',
  hideShadow: 'hideShadow Abigail',
  hospitaldeath: 'hospitaldeath',
  ignoreEventTileOffset: 'ignoreEventTileOffset',
  loadActors: 'loadActors',
  makeInvisible: 'makeInvisible Abigail',
  minedeath: 'minedeath',
  positionOffset: 'positionOffset Abigail 0 0',
  questionAnswered: 'questionAnswered',
  removeTile: 'removeTile "Back" 10 15',
  replaceWithClone: 'replaceWithClone Abigail',
  resetVariable: 'resetVariable',
  rustyKey: 'rustyKey',
  setSkipActions: 'setSkipActions',
  specificTemporarySprite: 'specificTemporarySprite 0 10 15',
  swimming: 'swimming',
  stopSwimming: 'stopSwimming',
  temporarySprite: 'temporarySprite 0 10 15',
  temporaryAnimatedSprite: 'temporaryAnimatedSprite 0 10 15',
  tossConcession: 'tossConcession',
  translateName: 'translateName',
  tutorialMenu: 'tutorialMenu',
  updateMinigame: 'updateMinigame',
  ambientLight: 'ambientLight 255 255 255',
  animalNaming: 'animalNaming',
}
