import os from 'node:os'
import path from 'node:path'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import type { CodeSplittingGroup } from 'rolldown'
import { defineConfig, type Plugin } from 'vite-plus'
import react, { reactCompilerPreset } from '@vitejs/plugin-react'
import babel from '@rolldown/plugin-babel'
import { resolveDevServerHost, resolveDevServerPorts } from './scripts/dev/tauriDevRuntime.mjs'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const host = resolveDevServerHost()
const { port, hmrPort } = resolveDevServerPorts()
const reactCompilerRuntimeInteropId = '\0modforge/react-compiler-runtime-interop'
export const REACT_DEVTOOLS_STANDALONE_SCRIPT_URL = 'http://localhost:8097'

function resolveViteCacheDir(env = process.env) {
  const systemCacheRoot =
    env.LOCALAPPDATA?.trim() || env.XDG_CACHE_HOME?.trim() || env.USERPROFILE?.trim() || path.join(os.homedir(), '.cache')

  return path.join(systemCacheRoot, 'ModForge Studio', 'vite')
}

type NamedChunkGroup = {
  name: string
  priority: number
  test: (normalizedId: string) => boolean
}

function normalizeModuleId(id: string) {
  return id.replaceAll('\\', '/')
}

export function shouldInjectReactDevtoolsStandalone(env = process.env) {
  return ['1', 'true', 'yes', 'on'].includes(
    String(env.MODFORGE_REACT_DEVTOOLS ?? '')
      .trim()
      .toLowerCase(),
  )
}

export function reactDevtoolsStandaloneHtmlPlugin(env = process.env): Plugin {
  return {
    name: 'modforge:react-devtools-standalone-html',
    apply: 'serve',
    transformIndexHtml() {
      if (!shouldInjectReactDevtoolsStandalone(env)) {
        return []
      }

      return [
        {
          tag: 'script',
          attrs: {
            src: REACT_DEVTOOLS_STANDALONE_SCRIPT_URL,
          },
          injectTo: 'head-prepend',
        },
      ]
    },
  }
}

/**
 * Vendor facade entries that back the plugin import map. Each entry re-exports
 * the host's own module instance (React singleton, jsx-runtime, plugin SDK, and
 * the shared UI/utility libraries) as a real ESM module with `export`
 * statements — rolldown internal chunks such as `react-vendor.js` have no
 * exports of their own, so the import map cannot point at them directly.
 * Emitted as fixed-name entries (`vendor/<name>.js`).
 *
 * Production vs dev sources:
 * - react / react-dom / react-jsx-runtime are CJS packages, and rolldown cannot
 *   statically enumerate `export *` names from CJS, so their production entries
 *   are virtual modules generated by pluginVendorFacadePlugin below with an
 *   explicit named-export list derived from the installed package at build time.
 * - Everything else is ESM, so its production entry is the static
 *   `vendor/<name>.ts` file (`export *` works).
 * - In dev, all facade URLs are served by pluginVendorDevMiddleware, which
 *   redirects to the static `vendor/<name>.ts` files; dev prebundling (esbuild)
 *   produces full ESM named surfaces, so plain `export *` is sufficient there.
 *
 * Exposed libraries are ones the host already bundles (plugins share the host
 * instances; facades add ~zero bytes). Plugin authors mark them external in
 * their bundler and install the npm package as a devDependency for types.
 * Libraries that require their own stylesheet (e.g. @xyflow/react) are not
 * exposed: import maps only resolve JS.
 */
const pluginVendorFacades = [
  'react',
  'react-dom',
  'react-jsx-runtime',
  'plugin-sdk',
  'dnd-kit-core',
  'dnd-kit-sortable',
  'dnd-kit-utilities',
  'floating-ui-react',
  'tanstack-react-virtual',
  'react-resizable-panels',
  'lucide-react',
  'zustand',
] as const

/** Bare import-map specifier backed by each facade entry. */
const pluginVendorImportSpecifiers: Record<(typeof pluginVendorFacades)[number], string> = {
  react: 'react',
  'react-dom': 'react-dom',
  'react-jsx-runtime': 'react/jsx-runtime',
  'plugin-sdk': '@modforge/plugin-sdk',
  'dnd-kit-core': '@dnd-kit/core',
  'dnd-kit-sortable': '@dnd-kit/sortable',
  'dnd-kit-utilities': '@dnd-kit/utilities',
  'floating-ui-react': '@floating-ui/react',
  'tanstack-react-virtual': '@tanstack/react-virtual',
  'react-resizable-panels': 'react-resizable-panels',
  'lucide-react': 'lucide-react',
  zustand: 'zustand',
}

const pluginVendorFacadeDir = path.resolve(__dirname, 'vendor')

/** CJS specs behind the virtual production facades, keyed by entry name. */
const pluginVendorCjsSpecs: Record<string, string> = {
  react: 'react',
  'react-dom': 'react-dom',
  'react-jsx-runtime': 'react/jsx-runtime',
}

const pluginVendorVirtualPrefix = '\0modforge:plugin-vendor/'

const pluginVendorRequire = createRequire(path.resolve(__dirname, 'package.json'))

/**
 * Generates the production vendor facades for the CJS packages above: virtual
 * modules containing explicit named re-exports plus a default re-export (the
 * jsx-runtime has no meaningful default). Deriving names from the installed
 * package keeps the facades correct across React upgrades.
 */
function pluginVendorFacadePlugin(): Plugin {
  return {
    name: 'modforge:plugin-vendor-facade',
    apply: 'build',
    resolveId(source: string) {
      return source.startsWith(pluginVendorVirtualPrefix) ? source : null
    },
    load(id: string) {
      if (!id.startsWith(pluginVendorVirtualPrefix)) {
        return null
      }
      const spec = pluginVendorCjsSpecs[id.slice(pluginVendorVirtualPrefix.length)]
      if (!spec) {
        return null
      }
      const names = Object.keys(pluginVendorRequire(spec)).filter((name) => name !== 'default')
      const lines = [`export { ${names.join(', ')} } from ${JSON.stringify(spec)}`]
      if (spec !== 'react/jsx-runtime') {
        lines.push(`export { default } from ${JSON.stringify(spec)}`)
      }
      return lines.join('\n')
    },
  }
}

/**
 * Injects an import map into the HTML head so that code-package plugins loaded
 * via `plugin://` can import react, react-dom, jsx-runtime, the plugin SDK and
 * the shared libraries as ESM singletons (matching the host's instances). The
 * import map URLs point to the fixed-name vendor facade entries emitted under
 * `vendor/`.
 *
 * In dev mode, the same URLs are served by pluginVendorDevMiddleware below,
 * which redirects each facade URL to the dev-transformed facade source (import
 * analysis then resolves bare specifiers to the optimized deps, sharing the
 * host's instances). If the webview does not support import maps, code-package
 * plugins are rejected by the loader (data-pack plugins are unaffected).
 */
function pluginImportMapHtmlPlugin(): Plugin {
  return {
    name: 'modforge:plugin-import-map',
    transformIndexHtml() {
      const importMap = {
        imports: Object.fromEntries(pluginVendorFacades.map((name) => [pluginVendorImportSpecifiers[name], `./vendor/${name}.js`])),
      }
      return [
        {
          tag: 'script',
          attrs: { type: 'importmap' },
          children: JSON.stringify(importMap),
          injectTo: 'head-prepend',
        },
      ]
    },
  }
}

/**
 * Serves the plugin vendor facade URLs in dev mode. Production emits real
 * `vendor/*.js` entries; in dev there is no dist output, so each facade URL
 * redirects to the same facade source through Vite's transform pipeline (the
 * `/@fs/` URL keeps the workspace path outside the project root servable).
 */
function pluginVendorDevMiddleware(): Plugin {
  return {
    name: 'modforge:plugin-vendor-dev-middleware',
    apply: 'serve',
    configureServer(server) {
      const facadePattern = new RegExp(`^/vendor/(${pluginVendorFacades.join('|')})\\.js$`)
      server.middlewares.use((req, res, next) => {
        const url = req.url?.split('?')[0] ?? ''
        const match = facadePattern.exec(url)
        if (!match) {
          next()
          return
        }

        const facadePath = path.join(pluginVendorFacadeDir, `${match[1]}.ts`).replaceAll('\\', '/')
        res.statusCode = 302
        res.setHeader('Location', `/@fs/${encodeURI(facadePath)}`)
        res.end()
      })
    },
  }
}

function reactCompilerRuntimeInteropPlugin() {
  return {
    name: 'modforge:react-compiler-runtime-interop',
    enforce: 'pre' as const,
    resolveId(source: string) {
      if (source === 'react/compiler-runtime') {
        return reactCompilerRuntimeInteropId
      }

      return null
    },
    load(id: string) {
      if (id !== reactCompilerRuntimeInteropId) {
        return null
      }

      return `
import React from 'react'

const ReactSharedInternals = React.__CLIENT_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE

export function c(size) {
  const dispatcher = ReactSharedInternals.H
  if (dispatcher === null && import.meta.env.DEV) {
    console.error(
      'Invalid hook call. Hooks can only be called inside of the body of a function component. See https://react.dev/link/invalid-hook-call for tips about how to debug and fix this problem.',
    )
  }

  return dispatcher.useMemoCache(size)
}

export default { c }
`
    },
  }
}

const namedChunkGroups: NamedChunkGroup[] = [
  {
    name: 'react-vendor',
    priority: 100,
    test: (id) => id.includes('/node_modules/react/') || id.includes('/node_modules/react-dom/'),
  },
  {
    name: 'desktop-host-vendor',
    priority: 90,
    test: (id) => id.includes('/node_modules/@tauri-apps/'),
  },
  {
    name: 'ui-vendor',
    priority: 80,
    test: (id) => id.includes('/node_modules/lucide-react/') || id.includes('/node_modules/@radix-ui/'),
  },
  {
    name: 'player-appearance',
    priority: 70,
    test: (id) =>
      id.includes('/src/app/app-shell/PlayerAppearanceWindow') ||
      id.includes('/src/entities/event/model/stage/playerAppearance') ||
      id.includes('/src/entities/event/model/stage/farmerAppearanceRenderer') ||
      id.includes('/src/entities/character/lib/clothingSprites'),
  },
  {
    name: 'event-condition-model',
    priority: 60,
    test: (id) =>
      id.includes('/src/entities/event/model/preconditionSemantics') ||
      id.includes('/src/entities/event/model/gameStateQueryCatalog') ||
      id.includes('/src/entities/event/model/gameStateQuerySemantics'),
  },
  {
    name: 'event-authoring-model',
    priority: 60,
    test: (id) =>
      id.includes('/src/entities/event/model/parser') ||
      id.includes('/src/entities/event/model/commandCatalog') ||
      id.includes('/src/entities/event/model/patchHub'),
  },
  {
    name: 'event-stage-effects',
    priority: 70,
    test: (id) => id.includes('/src/entities/event/model/stage/eventStageSpecificSprite'),
  },
  {
    name: 'event-stage-workflow-schemas',
    priority: 70,
    test: (id) => id.includes('/src/pages/workbench/workspaces/event-stage/editors/event-workflow/workflow-model/command-schemas/'),
  },
  {
    name: 'event-stage-workflow-model',
    priority: 69,
    test: (id) => id.includes('/src/pages/workbench/workspaces/event-stage/editors/event-workflow/workflow-model/'),
  },
  {
    name: 'resource-browser',
    priority: 69,
    test: (id) => id.includes('/src/features/resource-browser/'),
  },
  {
    name: 'event-stage-script-editor',
    priority: 69,
    test: (id) =>
      id.includes('/src/pages/workbench/workspaces/event-stage/editors/event-workflow/workflow-view/CommandPalette') ||
      id.includes('/src/pages/workbench/workspaces/event-stage/editors/event-workflow/workflow-view/ParamPill') ||
      id.includes('/src/pages/workbench/workspaces/event-stage/editors/event-workflow/workflow-view/ScriptCard') ||
      id.includes('/src/pages/workbench/workspaces/event-stage/editors/event-workflow/workflow-view/ScriptEditor') ||
      id.includes('/src/pages/workbench/workspaces/event-stage/editors/event-workflow/workflow-view/ScriptTimeline'),
  },
  {
    name: 'event-stage-preview',
    priority: 69,
    test: (id) =>
      id.includes('/src/pages/workbench/workspaces/event-stage/editors/event-workflow/workflow-view/ActorSprite') ||
      id.includes('/src/pages/workbench/workspaces/event-stage/editors/event-workflow/workflow-view/EventStagePreview') ||
      id.includes('/src/pages/workbench/workspaces/event-stage/editors/event-workflow/workflow-view/StagePathOverlay'),
  },
  {
    name: 'event-stage-workflow-view',
    priority: 68,
    test: (id) => id.includes('/src/pages/workbench/workspaces/event-stage/editors/event-workflow/workflow-view/'),
  },
  {
    name: 'event-stage-authoring',
    priority: 65,
    test: (id) => id.includes('/src/pages/workbench/workspaces/event-stage/editors/'),
  },
  {
    name: 'event-stage-runtime',
    priority: 60,
    test: (id) =>
      id.includes('/src/pages/workbench/workspaces/event-stage/') ||
      id.includes('/src/entities/event/model/stage/eventStageShared') ||
      id.includes('/src/entities/event/model/stage/eventStageAssets') ||
      id.includes('/src/entities/event/model/stage/eventStagePlayback') ||
      id.includes('/src/entities/event/model/stage/eventStageTemporarySprites') ||
      id.includes('/src/entities/event/model/stage/eventStageFarmerState') ||
      id.includes('/src/entities/event/model/stage/farmerEventAnimationData'),
  },
  {
    name: 'building-workspace-state',
    priority: 50,
    test: (id) =>
      id.includes('/src/pages/workbench/workspaces/building/state/') ||
      id.includes('/src/pages/workbench/workspaces/building/entities/building/'),
  },
  {
    name: 'building-workspace-view',
    priority: 50,
    test: (id) => id.includes('/src/pages/workbench/workspaces/building/view/'),
  },
  {
    name: 'building-workspace-panels',
    priority: 50,
    test: (id) => id.includes('/src/pages/workbench/ui/workspace-panels/building/'),
  },
  {
    name: 'building-workspace',
    priority: 40,
    test: (id) => id.includes('/src/pages/workbench/workspaces/building/'),
  },
  {
    name: 'item-workspace',
    priority: 40,
    test: (id) => id.includes('/src/pages/workbench/workspaces/item/'),
  },
  {
    name: 'character-workspace',
    priority: 40,
    test: (id) => id.includes('/src/pages/workbench/workspaces/character/'),
  },
  {
    name: 'mod-workspace',
    priority: 40,
    test: (id) => id.includes('/src/pages/workbench/workspaces/mod/'),
  },
  {
    name: 'character-data-workspace',
    priority: 40,
    test: (id) => id.includes('/src/pages/workbench/workspaces/character-data/'),
  },
  {
    name: 'dialogue-workspace',
    priority: 40,
    test: (id) => id.includes('/src/pages/workbench/workspaces/dialogue/'),
  },
  {
    name: 'schedule-workspace',
    priority: 40,
    test: (id) => id.includes('/src/pages/workbench/workspaces/schedule/'),
  },
  {
    name: 'mail-workspace',
    priority: 40,
    test: (id) => id.includes('/src/pages/workbench/workspaces/mail/'),
  },
  {
    name: 'debugger-workspace',
    priority: 40,
    test: (id) => id.includes('/src/pages/workbench/workspaces/debugger/'),
  },
  {
    name: 'map-workspace',
    priority: 40,
    test: (id) =>
      id.includes('/src/entities/map/ui/MapViewport') ||
      id.includes('/src/entities/map/') ||
      id.includes('/src/pages/workbench/workspaces/map/'),
  },
]

export function resolveRolldownChunkGroup(moduleId: string) {
  const normalizedId = normalizeModuleId(moduleId)

  return namedChunkGroups.find((group) => group.test(normalizedId))?.name ?? null
}

const rolldownChunkGroups: CodeSplittingGroup[] = namedChunkGroups.map(({ name, priority, test }) => ({
  name,
  priority,
  test: (id) => test(normalizeModuleId(id)),
}))

export default defineConfig({
  base: './',
  clearScreen: false,
  plugins: [
    reactDevtoolsStandaloneHtmlPlugin(),
    pluginImportMapHtmlPlugin(),
    pluginVendorDevMiddleware(),
    pluginVendorFacadePlugin(),
    reactCompilerRuntimeInteropPlugin(),
    react(),
    babel({ presets: [reactCompilerPreset()] }) as unknown as Plugin,
  ] as unknown as Plugin[],
  cacheDir: resolveViteCacheDir(),
  resolve: {
    alias: [
      { find: '@app', replacement: path.resolve(__dirname, 'src/app') },
      { find: '@pages', replacement: path.resolve(__dirname, 'src/pages') },
      { find: '@widgets', replacement: path.resolve(__dirname, 'src/widgets') },
      { find: '@features', replacement: path.resolve(__dirname, 'src/features') },
      { find: '@entities', replacement: path.resolve(__dirname, 'src/entities') },
      { find: '@shared', replacement: path.resolve(__dirname, 'src/shared') },
      { find: '@platform', replacement: path.resolve(__dirname, 'src/platform') },
      { find: '@test', replacement: path.resolve(__dirname, 'src/tests/support') },
      { find: /^@locales$/, replacement: path.resolve(__dirname, 'src/locales/index.ts') },
      { find: /^@locales\/(.*)$/, replacement: path.resolve(__dirname, 'src/locales/$1') },
    ],
  },
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./src/tests/support/setup.ts'],
    include: ['src/tests/**/*.{test,spec}.{ts,tsx}'],
    exclude: ['**/node_modules/**', '**/dist/**', 'src/dev/**'],
  },
  build: {
    manifest: true,
    rolldownOptions: {
      checks: {
        pluginTimings: false,
      },
      input: Object.fromEntries([
        ['index', path.resolve(__dirname, 'index.html')],
        // Vendor facade entries backing the plugin import map must have stable
        // URLs (no hash suffix) so that `plugin://`-loaded code packages can
        // resolve react, react-dom, jsx-runtime and the SDK via the import map.
        // CJS packages use generated virtual modules (explicit named exports);
        // the ESM plugin-sdk uses the static vendor/plugin-sdk.ts file.
        ...pluginVendorFacades.map((name) => {
          const spec = pluginVendorCjsSpecs[name]
          const source = spec ? `${pluginVendorVirtualPrefix}${name}` : path.resolve(pluginVendorFacadeDir, `${name}.ts`)
          return [name, source] as const
        }),
      ]),
      // App builds otherwise treeshake entry exports, which would strip the
      // vendor facades' re-export surface that the plugin import map relies on.
      preserveEntrySignatures: 'exports-only',
      output: {
        codeSplitting: {
          groups: rolldownChunkGroups,
        },
        entryFileNames: (chunkInfo: { name: string }) =>
          (pluginVendorFacades as readonly string[]).includes(chunkInfo.name) ? 'vendor/[name].js' : 'assets/[name]-[hash].js',
      },
    },
  },
  server: {
    port,
    strictPort: true,
    host,
    watch: {
      ignored: ['**/src-tauri/target/**'],
    },
    hmr: {
      protocol: 'ws',
      host,
      port: hmrPort,
    },
  },
})
