export {
  loadCharacterImageState,
  loadCharacterWorkspaceEntries,
  loadVanillaCharacterRecords,
  loadVanillaGiftTasteEntries,
  resolveLocalizedText,
  type CharacterImageState,
} from './api/characterAssets'
export { buildAbsoluteSpriteLayerStyle, buildSpriteStyle } from './lib/characterSprites'
export * from './lib/clothingSprites'
export {
  buildNpcGiftTasteBuckets,
  buildUniversalGiftTasteBuckets,
  createEmptyNpcGiftTasteEntry,
  GIFT_TASTE_KINDS,
  isUniversalGiftTasteKey,
  NPC_GIFT_TASTE_SLOT_COUNT,
  normalizeContextTag,
  normalizeTagFragment,
  parseGiftTasteTokenList,
  parseNpcGiftTasteEntry,
  parseQualifiedGiftTasteObjectId,
  serializeNpcGiftTasteEntry,
  UNIVERSAL_GIFT_TASTE_KEYS,
  type GiftTasteBuckets,
  type GiftTasteKind,
  type NpcGiftTasteEntry,
  type NpcGiftTasteSection,
} from './lib/giftTasteHelpers'
export { useCharacterAuthoringHandoff } from './model/authoringHandoff'
export {
  addCharacterEntry,
  AGE_VALUES,
  CALENDAR_VALUES,
  CHARACTER_FIELD_ORDER,
  createMinimalCharacterEntry,
  DEFAULT_HOME_DIRECTION,
  displayNameFromNpcId,
  END_SLIDE_SHOW_VALUES,
  findCharacterAssetPatchState,
  GENDER_VALUES,
  HOME_DIRECTION_VALUES,
  HOME_REGION_SUGGESTIONS,
  LANGUAGE_VALUES,
  MANNER_VALUES,
  MOD_ID_TOKEN_PREFIX,
  OPTIMISM_VALUES,
  SEASON_VALUES,
  SOCIAL_ANXIETY_VALUES,
  SOCIAL_TAB_VALUES,
  validateHomePlacement,
  type AddCharacterEntryResult,
  type CharacterAppearanceEntry,
  type CharacterAssetPatchInput,
  type CharacterAssetPatchState,
  type CharacterDataFields,
  type CharacterHomeEntry,
  type CharacterHomePlacement,
  type CharacterHomePlacementError,
  type CharacterPoint,
  type CharacterRect,
  type CharacterShadow,
  type WinterStarGiftEntry,
} from './model/characterFields'
export {
  buildCharacterAppearanceVariants,
  buildGameContentPath,
  CHARACTER_DATA_ASSET_PATH,
  CHARACTER_GIFT_TASTES_ASSET_PATH,
  createCharacterEntryIndex,
  createCharacterWorkspaceEntry,
  EMPTY_CHARACTER_VISUAL_ASSET_STATE,
  getCharacterPortraitFrameCount,
  mergeCharacterAppearanceOverride,
  MONSTER_DATA_ASSET_PATH,
  normalizeCharacterAssetName,
  OBJECT_DATA_ASSET_PATH,
  resolveCharacterVariantPaths,
  SPRING_OBJECTS_ASSET_PATH,
  type CharacterAppearanceVariant,
  type CharacterDataEntry,
  type CharacterGiftGroup,
  type CharacterGiftGroupKind,
  type CharacterGiftItem,
  type CharacterVisualAssetState,
  type CharacterWorkspaceEntry,
} from './model/characterIndex'
export { CHARACTER_DATA_ASSET_ID, CHARACTER_DATA_SCHEMA } from './model/characterSchema'
export { NPC_GIFT_TASTES_ASSET_ID, validateCharacterEntries, validateGiftTasteEntries } from './model/validation'
export {
  CHARACTER_WALK_DIRECTIONS,
  CharacterBreathingCanvas,
  CharacterSpriteThumbnail,
  CharacterWalkCycleGrid,
  CharacterWalkCycleTile,
  resolveCharacterSpriteMetrics,
  type CharacterSpriteMetrics,
} from './ui/CharacterSpritePreview'
