import { HOST_COMMANDS } from '@platform/host-commands'
import type { HostCommandPolicy } from '@platform/host-command-client'
import type { SaveDialogOptions } from '@shared/contracts'
import { canUseDesktopHost, getPlatformPorts, invokeDesktop } from './runtime'

const fileExportPolicy = { kind: 'exclusiveMutation', resource: 'FileExport' } satisfies HostCommandPolicy

/** Describes bytes and save-dialog metadata for a user-initiated file export. */
export type FileContentSaveRequest = {
  bytes: Uint8Array
  dialog: SaveDialogOptions
  fileName: string
  mediaType: string
}

function encodeBase64(bytes: Uint8Array) {
  let binary = ''
  for (let offset = 0; offset < bytes.length; offset += 0x8000) {
    binary += String.fromCharCode(...bytes.subarray(offset, offset + 0x8000))
  }
  return btoa(binary)
}

function downloadFile(request: FileContentSaveRequest) {
  const url = URL.createObjectURL(new Blob([request.bytes as BlobPart], { type: request.mediaType }))
  const link = document.createElement('a')
  link.href = url
  link.download = request.fileName
  link.hidden = true
  document.body.append(link)
  link.click()
  link.remove()
  window.setTimeout(() => URL.revokeObjectURL(url), 0)
}

/** Saves generated bytes through the desktop host or the browser download fallback. */
export async function saveFileContent(request: FileContentSaveRequest): Promise<'saved' | 'cancelled'> {
  if (!canUseDesktopHost()) {
    downloadFile(request)
    return 'saved'
  }

  const outputPath = await getPlatformPorts().dialog.saveFile(request.dialog)
  if (!outputPath) return 'cancelled'

  await invokeDesktop<void>(HOST_COMMANDS.exportFile, { outputPath, contentBase64: encodeBase64(request.bytes) }, fileExportPolicy)
  return 'saved'
}
