import type { LauncherPort } from '@features/launcher/model/launcherPort'
import {
  loadLauncherSettings,
  saveLauncherSettings,
  loadLauncherLibraryState,
  saveLauncherLibraryState,
  loadLauncherLibraryCovers,
  setLauncherLibraryCover,
  persistLauncherLibraryRemoteCover,
  loadLauncherDownloadQueue,
  saveLauncherDownloadQueue,
  searchLauncherCatalog,
  loadLauncherRemoteModDetail,
  loadLauncherUpdateChangelog,
  loadLauncherNexusDiagnostics,
  restartLauncherNexusDiagnostics,
  setLauncherNexusForceOffline,
  resolveLauncherImage,
  loadCachedLauncherUpdates,
  loadSuppressedLauncherUpdateModIds,
  checkLauncherUpdates,
  listenToLauncherUpdateProgress,
  downloadLauncherMod,
  installLauncherArchive,
  listLauncherInstallBackups,
  restoreLauncherInstallBackup,
  inspectLauncherArchive,
  launchLauncherGame,
  openLauncherPath,
  openLauncherUrl,
  scanLauncherLibrary,
  clearLauncherLibraryReadCaches,
  chooseArchiveFile,
  chooseImageFile,
  getLauncherBackupDirectory,
  setLauncherModEnabled,
  chooseDirectory,
  detectDefaultGameDirectory,
  subscribeLauncherUpdates,
  toDesktopAssetUrl,
} from '@platform/desktop'

export function createLauncherPortAdapter(): LauncherPort {
  return {
    loadSettings: () => loadLauncherSettings(),
    saveSettings: (request) => saveLauncherSettings(request),
    scanLibrary: (request) => scanLauncherLibrary(request),
    loadLibraryState: () => loadLauncherLibraryState(),
    saveLibraryState: (request) => saveLauncherLibraryState(request),
    loadLibraryCovers: () => loadLauncherLibraryCovers(),
    setLibraryCover: (request) => setLauncherLibraryCover(request),
    persistLibraryRemoteCover: (request) => persistLauncherLibraryRemoteCover(request),
    loadDownloadQueue: () => loadLauncherDownloadQueue(),
    saveDownloadQueue: (request) => saveLauncherDownloadQueue(request),
    searchCatalog: (request) => searchLauncherCatalog(request),
    loadRemoteModDetail: (request) => loadLauncherRemoteModDetail(request),
    loadUpdateChangelog: (request) => loadLauncherUpdateChangelog(request),
    loadNexusDiagnostics: () => loadLauncherNexusDiagnostics(),
    restartNexusDiagnostics: () => restartLauncherNexusDiagnostics(),
    setNexusForceOffline: (forceOffline) => setLauncherNexusForceOffline(forceOffline),
    resolveImage: (request) => resolveLauncherImage(request),
    loadCachedUpdates: (request) => loadCachedLauncherUpdates(request),
    loadSuppressedUpdateModIds: (request) => loadSuppressedLauncherUpdateModIds(request),
    checkUpdates: (request) => checkLauncherUpdates(request),
    listenToUpdateProgress: (listener) => listenToLauncherUpdateProgress(listener),
    downloadMod: (request) => downloadLauncherMod(request),
    installArchive: (request) => installLauncherArchive(request),
    listInstallBackups: (request) => listLauncherInstallBackups(request),
    restoreInstallBackup: (request) => restoreLauncherInstallBackup(request),
    inspectArchive: (request) => inspectLauncherArchive(request),
    launchGame: () => launchLauncherGame(),
    openPath: (request) => openLauncherPath(request),
    openUrl: (request) => openLauncherUrl(request),
    clearLibraryReadCaches: (modsPath) => clearLauncherLibraryReadCaches(modsPath),
    chooseArchiveFile: (title) => chooseArchiveFile(title),
    chooseImageFile: (title) => chooseImageFile(title),
    getBackupDirectory: () => getLauncherBackupDirectory(),
    setModEnabled: (request) => setLauncherModEnabled(request),
    chooseDirectory: (title) => chooseDirectory(title),
    detectDefaultGameDirectory: () => detectDefaultGameDirectory(),
    toDesktopAssetUrl: (path, protocol) => toDesktopAssetUrl(path, protocol),
    subscribeUpdates: (modsPath, listener) => subscribeLauncherUpdates(modsPath, listener),
  }
}
