import type { LauncherPort } from '@features/launcher/model/launcherPort'
import {
  startNexusSso,
  getNexusSsoStatus,
  cancelNexusSso,
  validateNexusApiKey,
  loadLauncherSettings,
  saveLauncherSettings,
  loadLauncherLibraryState,
  saveLauncherLibraryState,
  loadLauncherLibraryCovers,
  loadLauncherImageFailures,
  recordLauncherImageFailure,
  setLauncherLibraryCover,
  persistLauncherLibraryRemoteCover,
  loadLauncherDownloadQueue,
  saveLauncherDownloadQueue,
  searchLauncherCatalog,
  isLauncherRemoteModIdInvalid,
  markLauncherRemoteModIdInvalid,
  loadLauncherRemoteModDetail,
  loadLauncherUpdateChangelog,
  loadLauncherNexusDiagnostics,
  restartLauncherNexusDiagnostics,
  retryLauncherNexusDiagnosticsRoute,
  setLauncherNexusForceOffline,
  resolveCachedLauncherImage,
  resolveLauncherImage,
  loadCachedLauncherUpdates,
  loadSuppressedLauncherUpdateModIds,
  checkLauncherUpdates,
  listenToLauncherImageFetchDisconnected,
  listenToLauncherUpdateProgress,
  downloadLauncherMod,
  cancelLauncherDownload,
  listenToLauncherDownloadProgress,
  installLauncherArchive,
  listLauncherInstallBackups,
  restoreLauncherInstallBackup,
  inspectLauncherArchive,
  launchLauncherGame,
  openLauncherPath,
  openLauncherUrl,
  scanLauncherLibrary,
  loadLauncherRuntimeInfo,
  clearLauncherLibraryReadCaches,
  getLauncherBackupDirectory,
  setLauncherModEnabled,
  subscribeLauncherUpdates,
} from '@features/launcher/api'
import { detectDefaultGameDirectory } from '@entities/game/api'
import { reportAppEvent } from '@platform/observability'
import { chooseArchiveFile, chooseDirectory, chooseImageFile, toDesktopAssetUrl } from '@platform/host'

export function createLauncherPortAdapter(): LauncherPort {
  return {
    loadSettings: () => loadLauncherSettings(),
    writeDebugLog: (request) =>
      reportAppEvent({
        level: 'debug',
        title: request.message,
        notify: false,
        logMessage: request.message,
        keyValues: request.keyValues,
      }),
    saveSettings: (request) => saveLauncherSettings(request),
    scanLibrary: (request) => scanLauncherLibrary(request),
    loadRuntimeInfo: () => loadLauncherRuntimeInfo(),
    loadLibraryState: () => loadLauncherLibraryState(),
    saveLibraryState: (request) => saveLauncherLibraryState(request),
    loadLibraryCovers: () => loadLauncherLibraryCovers(),
    loadImageFailures: () => loadLauncherImageFailures(),
    recordImageFailure: (request) => recordLauncherImageFailure(request),
    setLibraryCover: (request) => setLauncherLibraryCover(request),
    persistLibraryRemoteCover: (request) => persistLauncherLibraryRemoteCover(request),
    loadDownloadQueue: () => loadLauncherDownloadQueue(),
    saveDownloadQueue: (request) => saveLauncherDownloadQueue(request),
    searchCatalog: (request) => searchLauncherCatalog(request),
    isRemoteModIdInvalid: (modId) => isLauncherRemoteModIdInvalid(modId),
    markRemoteModIdInvalid: (modId) => markLauncherRemoteModIdInvalid(modId),
    loadRemoteModDetail: (request) => loadLauncherRemoteModDetail(request),
    loadUpdateChangelog: (request) => loadLauncherUpdateChangelog(request),
    loadNexusDiagnostics: () => loadLauncherNexusDiagnostics(),
    restartNexusDiagnostics: () => restartLauncherNexusDiagnostics(),
    retryNexusDiagnosticsRoute: (routeId) => retryLauncherNexusDiagnosticsRoute(routeId),
    setNexusForceOffline: (forceOffline) => setLauncherNexusForceOffline(forceOffline),
    resolveCachedImage: (request) => resolveCachedLauncherImage(request),
    resolveImage: (request) => resolveLauncherImage(request),
    loadCachedUpdates: (request) => loadCachedLauncherUpdates(request),
    loadSuppressedUpdateModIds: (request) => loadSuppressedLauncherUpdateModIds(request),
    checkUpdates: (request) => checkLauncherUpdates(request),
    listenToUpdateProgress: (listener) => listenToLauncherUpdateProgress(listener),
    listenToImageFetchDisconnected: (listener) => listenToLauncherImageFetchDisconnected(listener),
    downloadMod: (request) => downloadLauncherMod(request),
    cancelDownload: (downloadId) => cancelLauncherDownload(downloadId),
    listenToDownloadProgress: (listener) => listenToLauncherDownloadProgress(listener),
    installArchive: (request) => installLauncherArchive(request),
    listInstallBackups: (request) => listLauncherInstallBackups(request),
    restoreInstallBackup: (request) => restoreLauncherInstallBackup(request),
    inspectArchive: (request) => inspectLauncherArchive(request),
    launchGame: () => launchLauncherGame(),
    openPath: (request) => openLauncherPath(request),
    openUrl: (request) => openLauncherUrl(request),
    clearLibraryReadCaches: (modsPath) => clearLauncherLibraryReadCaches(modsPath),
    chooseArchiveFile: (title) => chooseArchiveFile(title),
    chooseImageFile: (title) => chooseImageFile(title),
    getBackupDirectory: () => getLauncherBackupDirectory(),
    setModEnabled: (request) => setLauncherModEnabled(request),
    chooseDirectory: (title) => chooseDirectory(title),
    detectDefaultGameDirectory: () => detectDefaultGameDirectory(),
    toDesktopAssetUrl: (path, protocol) => toDesktopAssetUrl(path, protocol),
    subscribeUpdates: (modsPath, listener) => subscribeLauncherUpdates(modsPath, listener),
    validateNexusApiKey: () => validateNexusApiKey(),
    startNexusSso: () => startNexusSso(),
    getNexusSsoStatus: () => getNexusSsoStatus(),
    cancelNexusSso: () => cancelNexusSso(),
  }
}
