import { useMemo, type ReactNode } from 'react'
import { LocalizationProvider } from '@entities/localization'
import {
  cancelLocalizationJob,
  clearAiUsage,
  copyTranslationMemory,
  createLocalizationProfile,
  deleteLocalizationGlossary,
  deleteLocalizationProfile,
  deleteTranslationMemory,
  exportAiUsage,
  exportLocalizationKnowledge,
  importLocalizationKnowledge,
  inspectOfficialLocalizationIndex,
  listLocalizationGlossary,
  listLocalizationScopes,
  loadLocalizationScope,
  loadLocalizationStyle,
  queryAiUsageRecords,
  queryAiUsageSummary,
  rebuildOfficialLocalizationIndex,
  recordConfirmedTranslations,
  removeLocalizationProfileBinding,
  renameLocalizationProfile,
  resolveLocalizationScope,
  setLocalizationProfileBinding,
  saveLocalizationScopeSettings,
  saveLocalizationStyle,
  searchOfficialLocalization,
  searchTranslationMemory,
  upsertLocalizationGlossary,
  loadMachineTranslationSettings,
  saveMachineTranslationSettings,
  listMachineTranslationLanguages,
  testMachineTranslationProfile,
  translateLocalizationBatch,
  listenToOfficialLocalizationIndexProgress,
  cancelAiJob,
  reviewLocalizationBatch,
  listLocalizationReviewRuns,
  loadLocalizationReviewRun,
  updateLocalizationReviewIssues,
  loadLocalizationSemanticSettings,
  saveLocalizationSemanticSettings,
  inspectLocalizationSemanticModel,
  verifyLocalizationSemanticModel,
  probeLocalizationSemanticSearch,
  downloadLocalizationSemanticModel,
  deleteLocalizationSemanticModel,
  openLocalizationSemanticModelDirectory,
  inspectLocalizationSemanticIndex,
  rebuildLocalizationSemanticIndex,
  syncLocalizationSemanticIndex,
  listenToLocalizationSemanticProgress,
  testLocalizationSemanticRemoteProfile,
  loadLocalizationDefaultEngine,
  saveLocalizationDefaultEngine,
  initializeLocalizationPlan,
  acquireLocalizationSemanticRuntime,
  releaseLocalizationSemanticRuntime,
  unloadLocalizationSemanticRuntime,
  inspectLocalizationContext,
} from '@platform/host'
import type { LocalizationPort } from '@shared/contracts'
import { usePlatformPorts } from './usePlatformPorts'

export function LocalizationPlatformProvider({ children }: { children: ReactNode }) {
  const { dialog } = usePlatformPorts()
  const port = useMemo<LocalizationPort>(
    () => ({
      loadSemanticSettings: loadLocalizationSemanticSettings,
      saveSemanticSettings: saveLocalizationSemanticSettings,
      inspectSemanticModel: inspectLocalizationSemanticModel,
      verifySemanticModel: verifyLocalizationSemanticModel,
      probeSemanticSearch: probeLocalizationSemanticSearch,
      downloadSemanticModel: downloadLocalizationSemanticModel,
      deleteSemanticModel: deleteLocalizationSemanticModel,
      openSemanticModelDirectory: openLocalizationSemanticModelDirectory,
      inspectSemanticIndex: inspectLocalizationSemanticIndex,
      rebuildSemanticIndex: rebuildLocalizationSemanticIndex,
      syncSemanticIndex: syncLocalizationSemanticIndex,
      listenSemanticProgress: listenToLocalizationSemanticProgress,
      testSemanticRemoteProfile: testLocalizationSemanticRemoteProfile,
      chooseSemanticModelDirectory: () => dialog.chooseDirectory(),
      loadDefaultEngine: loadLocalizationDefaultEngine,
      saveDefaultEngine: saveLocalizationDefaultEngine,
      loadMachineTranslationSettings,
      saveMachineTranslationSettings,
      listMachineTranslationLanguages,
      testMachineTranslationProfile,
      translateBatch: translateLocalizationBatch,
      listenOfficialIndexProgress: listenToOfficialLocalizationIndexProgress,
      reviewBatch: reviewLocalizationBatch,
      listReviewRuns: listLocalizationReviewRuns,
      loadReviewRun: loadLocalizationReviewRun,
      updateReviewIssues: updateLocalizationReviewIssues,
      queryUsageSummary: queryAiUsageSummary,
      queryUsageRecords: queryAiUsageRecords,
      exportUsage: exportAiUsage,
      clearUsage: clearAiUsage,
      inspectOfficialIndex: inspectOfficialLocalizationIndex,
      chooseGameDirectory: () => dialog.chooseDirectory('Select the Stardew Valley game folder'),
      rebuildOfficialIndex: rebuildOfficialLocalizationIndex,
      searchOfficial: searchOfficialLocalization,
      cancelJob: async (jobId) => {
        await Promise.allSettled([cancelLocalizationJob(jobId), cancelAiJob(jobId)])
      },
      initializePlan: initializeLocalizationPlan,
      acquireSemanticRuntime: acquireLocalizationSemanticRuntime,
      releaseSemanticRuntime: releaseLocalizationSemanticRuntime,
      unloadSemanticRuntime: unloadLocalizationSemanticRuntime,
      inspectContext: inspectLocalizationContext,
      resolveScope: resolveLocalizationScope,
      createProfile: createLocalizationProfile,
      renameProfile: renameLocalizationProfile,
      deleteProfile: deleteLocalizationProfile,
      setProfileBinding: setLocalizationProfileBinding,
      removeProfileBinding: removeLocalizationProfileBinding,
      listScopes: listLocalizationScopes,
      loadScope: loadLocalizationScope,
      saveScopeSettings: saveLocalizationScopeSettings,
      listGlossary: listLocalizationGlossary,
      upsertGlossary: upsertLocalizationGlossary,
      deleteGlossary: deleteLocalizationGlossary,
      loadStyle: loadLocalizationStyle,
      saveStyle: saveLocalizationStyle,
      searchMemory: searchTranslationMemory,
      recordConfirmed: recordConfirmedTranslations,
      deleteMemory: deleteTranslationMemory,
      copyMemory: copyTranslationMemory,
      importKnowledge: importLocalizationKnowledge,
      exportKnowledge: exportLocalizationKnowledge,
      chooseKnowledgeImport: (format) =>
        dialog.chooseFile({
          filters: [
            {
              name: 'Localization knowledge',
              extensions: [format === 'knowledge-pack-json' ? 'json' : format === 'glossary-csv' ? 'csv' : 'tmx'],
            },
          ],
        }),
      chooseKnowledgeExport: (format) =>
        dialog.saveFile({
          defaultPath:
            format === 'knowledge-pack-json'
              ? 'modforge-knowledge.json'
              : format === 'glossary-csv'
                ? 'glossary.csv'
                : 'translation-memory.tmx',
          filters: [
            {
              name: 'Localization knowledge',
              extensions: [format === 'knowledge-pack-json' ? 'json' : format === 'glossary-csv' ? 'csv' : 'tmx'],
            },
          ],
        }),
    }),
    [dialog],
  )
  return <LocalizationProvider port={port}>{children}</LocalizationProvider>
}
