import { vi } from 'vite-plus/test'
import type { LauncherPort } from '@features/launcher/model/launcherPort'

export function createMockLauncherPort(overrides: Partial<LauncherPort> = {}): LauncherPort {
  const defaultSettings = {
    gamePath: null,
    modsPath: null,
    downloadPath: null,
    nexusApiKey: null,
    autoInstallDownloads: false,
    keepDownloadedArchives: false,
    autoCheckModUpdates: true,
  }

  const unimplemented = (method: keyof LauncherPort) =>
    vi.fn(() => {
      throw new Error(`LauncherPort.${method} was called without an explicit test override.`)
    })

  return {
    loadSettings: vi.fn().mockResolvedValue({
      ...defaultSettings,
    }),
    writeDebugLog: vi.fn(),
    saveSettings: vi.fn().mockImplementation(async (request) => ({
      ...defaultSettings,
      ...request,
    })),
    scanLibrary: vi.fn().mockResolvedValue({ modsPath: '', mods: [] }),
    loadRuntimeInfo: vi.fn().mockResolvedValue({
      gameVersion: null,
      smapiVersion: null,
    }),
    loadGmcmProbeDiagnostics: vi.fn().mockResolvedValue({
      status: 'ready' as const,
      probeAssemblyPath: 'E:\\ModForge Studio\\gmcm-probe\\modforge-gmcm-probe.dll',
      dotnetPath: 'dotnet',
      dotnetAvailable: true,
      net6RuntimeAvailable: true,
      installedRuntimes: ['Microsoft.NETCore.App 6.0.36 [C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App]'],
      warnings: [],
      repairActions: [],
    }),
    loadLibraryState: vi.fn().mockResolvedValue({
      storageFolders: [],
      hiddenModKeys: [],
      packPresets: [],
      childModGroups: [],
      libraryFolders: [],
      customOrders: {},
      currentPackId: null,
      scopeMode: 'all' as const,
    }),
    saveLibraryState: unimplemented('saveLibraryState'),
    loadLibraryCovers: unimplemented('loadLibraryCovers'),
    loadImageFailures: vi.fn().mockResolvedValue({ entries: [] }),
    recordImageFailure: vi.fn().mockResolvedValue({ entries: [] }),
    setLibraryCover: unimplemented('setLibraryCover'),
    persistLibraryRemoteCover: unimplemented('persistLibraryRemoteCover'),
    loadDownloadQueue: vi.fn().mockResolvedValue({ items: [] }),
    saveDownloadQueue: unimplemented('saveDownloadQueue'),
    searchCatalog: unimplemented('searchCatalog'),
    isRemoteModIdInvalid: vi.fn().mockReturnValue(false),
    markRemoteModIdInvalid: vi.fn(),
    loadRemoteModDetail: unimplemented('loadRemoteModDetail'),
    loadUpdateChangelog: unimplemented('loadUpdateChangelog'),
    loadNexusDiagnostics: vi.fn().mockResolvedValue({
      routes: [
        {
          routeId: 'publicGraphql',
          label: 'Nexus Public GraphQL',
          endpoint: 'https://api.nexusmods.com/v2/graphql',
          status: 'success' as const,
          attempts: 1,
          maxAttempts: 3,
          available: true,
          message: 'Connected after 1 attempt.',
        },
      ],
    }),
    restartNexusDiagnostics: vi.fn().mockResolvedValue({ routes: [] }),
    retryNexusDiagnosticsRoute: vi.fn().mockResolvedValue({ routes: [] }),
    setNexusForceOffline: vi.fn().mockResolvedValue({ routes: [] }),
    resolveCachedImage: vi.fn().mockResolvedValue(null),
    resolveImage: unimplemented('resolveImage'),
    loadCachedUpdates: vi.fn().mockResolvedValue(null),
    loadSuppressedUpdateModIds: vi.fn().mockResolvedValue({ modsPath: '', modIds: [] }),
    checkUpdates: unimplemented('checkUpdates'),
    listenToUpdateProgress: vi.fn().mockResolvedValue(() => {}),
    listenToImageFetchDisconnected: vi.fn().mockResolvedValue(() => {}),
    downloadMod: unimplemented('downloadMod'),
    cancelDownload: vi.fn().mockResolvedValue(undefined),
    listenToDownloadProgress: vi.fn().mockResolvedValue(() => {}),
    installArchive: unimplemented('installArchive'),
    listInstallBackups: unimplemented('listInstallBackups'),
    restoreInstallBackup: unimplemented('restoreInstallBackup'),
    inspectArchive: unimplemented('inspectArchive'),
    launchGame: unimplemented('launchGame'),
    openPath: unimplemented('openPath'),
    openUrl: unimplemented('openUrl'),
    clearLibraryReadCaches: vi.fn(),
    chooseArchiveFile: unimplemented('chooseArchiveFile'),
    chooseImageFile: unimplemented('chooseImageFile'),
    getBackupDirectory: unimplemented('getBackupDirectory'),
    setModEnabled: unimplemented('setModEnabled'),
    loadModConfig: vi.fn().mockResolvedValue({
      modPath: '',
      configPath: '',
      configExists: false,
      fields: [],
      schemaSources: [],
      warnings: [],
      probeStatus: 'not-run' as const,
    }),
    saveModConfig: vi.fn().mockImplementation(async (request) => ({
      modPath: request.modPath,
      configPath: `${request.modPath}/config.json`,
      configExists: true,
      fields: [],
      schemaSources: [],
      warnings: [],
      probeStatus: 'not-run' as const,
    })),
    loadConfigItems: vi.fn().mockResolvedValue([]),
    chooseDirectory: unimplemented('chooseDirectory'),
    detectDefaultGameDirectory: vi.fn().mockResolvedValue(null),
    toDesktopAssetUrl: vi.fn().mockReturnValue(''),
    validateNexusApiKey: vi.fn().mockResolvedValue({
      userName: 'TestUser',
      avatarUrl: null,
      profileUrl: null,
      isPremium: true,
      dailyRemaining: 950,
      hourlyRemaining: 450,
      dailyResetAt: null,
      hourlyResetAt: null,
    }),
    startNexusSso: vi.fn().mockResolvedValue({ ssoId: 'test-sso-id', status: 'connecting' as const }),
    getNexusSsoStatus: vi.fn().mockResolvedValue({
      status: 'idle' as const,
      errorKind: null,
      errorMessage: null,
      userName: null,
      isPremium: false,
      ssoId: null,
    }),
    cancelNexusSso: vi.fn().mockResolvedValue(undefined),

    subscribeUpdates: vi.fn().mockReturnValue(() => {}),
    ...overrides,
  }
}
